import type { AggregationRule } from "./schema";

export const SAMPLE_AGGREGATION_RULES: AggregationRule[] = [
  {
    children: [],
    description: "Base income rollup from mapped atomic categories.",
    includeCategoryIds: [
      "interest_income",
      "rental_income",
      "service_income",
      "other_income",
    ],
    label: "Income Base",
    nodeId: "income_base",
    nodeType: "group",
    operation: "sum",
    order: 10,
  },
  {
    children: [],
    description: "Base expense rollup from mapped atomic categories.",
    includeCategoryIds: ["bank_fees", "professional_fees", "interest_expense"],
    label: "Expense Base",
    nodeId: "expense_base",
    nodeType: "group",
    operation: "sum",
    order: 20,
  },
  {
    children: [],
    description: "Demonstrates subtracting one rollup from another.",
    label: "Income After Expenses",
    nodeId: "income_after_expenses",
    nodeType: "group",
    operands: [
      { label: "Income Base", refId: "income_base", refType: "node" },
      { label: "Expense Base", refId: "expense_base", refType: "node" },
    ],
    operation: "subtract",
    order: 30,
  },
  {
    children: [],
    description: "Draft adjustment factor used by Result Z.",
    label: "Z Adjustment Factor",
    nodeId: "z_adjustment_factor",
    nodeType: "constant",
    operation: "pass_through",
    order: 40,
    value: 1,
  },
  {
    children: [],
    label: "Result Z",
    nodeId: "Z",
    nodeType: "final_result",
    operands: [
      { label: "Income Base", refId: "income_base", refType: "node" },
      {
        label: "Z Adjustment Factor",
        refId: "z_adjustment_factor",
        refType: "node",
      },
    ],
    operation: "multiply",
    order: 50,
    resultName: "Z",
  },
  {
    children: [],
    label: "Result W",
    nodeId: "W",
    nodeType: "final_result",
    operands: [
      { label: "Expense Base", refId: "expense_base", refType: "node" },
    ],
    operation: "sum",
    order: 60,
    resultName: "W",
  },
  {
    children: [],
    description: "Demonstrates addition of two rollups.",
    label: "Optional Check Total",
    nodeId: "optional_check_total",
    nodeType: "formula",
    operands: [
      { label: "Income Base", refId: "income_base", refType: "node" },
      { label: "Expense Base", refId: "expense_base", refType: "node" },
    ],
    operation: "add",
    order: 70,
  },
];
