import type { ToolDefinition } from "../../../runtime/types";

export const categoryRollupAggregatorDefinition: ToolDefinition = {
  defaultConfig: {},
  description:
    "Groups mapped rows by category and applies rollup rules to produce subtotal buckets.",
  displayName: "Category Rollup Aggregator",
  family: "Logic",
  inputRoles: [
    {
      acceptedFamilies: ["Logic"],
      acceptedOutputTypes: ["mapped_rows"],
      allowMultiple: true,
      description: "Rows mapped by Keyword Mapper into atomic categories.",
      id: "mapped_rows",
      label: "Mapped rows",
      required: true,
    },
    {
      acceptedFamilies: ["Source"],
      acceptedOutputTypes: ["rollup_rules", "aggregation_rules"],
      acceptedSourceKinds: ["rollup_rules", "aggregation_rules"],
      allowMultiple: true,
      description: "Rollup rules that group mapped categories into subtotals.",
      id: "rollup_rules",
      label: "Rollup rules",
      required: true,
    },
  ],
  outputRoles: [
    {
      canRouteToFamilies: ["Logic", "Output", "Review / Validation"],
      description: "Totals by mapped category.",
      id: "category_totals",
      label: "Category totals",
      outputKey: "categoryTotals",
      outputType: "category_totals",
    },
    {
      canRouteToFamilies: ["Logic", "Output", "Review / Validation"],
      description: "Totals by rollup rule.",
      id: "rollup_totals",
      label: "Rollup totals",
      outputKey: "rollupTotals",
      outputType: "rollup_totals",
    },
    {
      canRouteToFamilies: ["Logic", "Output", "Review / Validation"],
      description:
        "Category and rollup totals exposed as named numeric values.",
      id: "named_values",
      label: "Named values",
      outputKey: "namedValues",
      outputType: "named_values",
    },
    {
      canRouteToFamilies: ["Output", "Review / Validation"],
      description: "Rows included by category.",
      id: "included_rows_by_category",
      label: "Included rows by category",
      outputKey: "includedRowsByCategory",
      outputType: "included_rows",
    },
    {
      canRouteToFamilies: ["Output", "Review / Validation"],
      description: "Rows included by rollup.",
      id: "included_rows_by_rollup",
      label: "Included rows by rollup",
      outputKey: "includedRowsByRollup",
      outputType: "included_rows",
    },
    {
      canRouteToFamilies: ["Output", "Review / Validation"],
      description: "Mapped rows not included by any rollup rule.",
      id: "excluded_rows",
      label: "Excluded rows",
      outputKey: "excludedRows",
      outputType: "excluded_rows",
    },
    {
      canRouteToFamilies: ["Output", "Review / Validation"],
      description: "Trace of category summing and rollup calculations.",
      id: "rollup_formula_trace",
      label: "Rollup trace",
      outputKey: "rollupFormulaTrace",
      outputType: "rollup_formula_trace",
    },
    {
      canRouteToFamilies: ["Output", "Review / Validation"],
      description: "Summary of rollup execution.",
      id: "rollup_summary",
      label: "Rollup summary",
      outputKey: "rollupSummary",
      outputType: "rollup_summary",
    },
  ],
  runMode: "local_mock",
  subtype: "Category Rollup Aggregator",
  toolGroup: "calculation",
  toolId: "logic.category_rollup_aggregator",
};
