export const EXPANDED_MAPPING_PIPELINE_ROWS = [
  {
    account: "4000",
    amount: 100,
    currency: "USD",
    description: "Interest earned on bank deposit",
    label: "Interest income",
    rowId: "row-001",
  },
  {
    account: "4010",
    amount: 60,
    currency: "USD",
    description: "Interest earned from short-term deposits",
    label: "Bank interest revenue",
    rowId: "row-002",
  },
  {
    account: "4100",
    amount: 220,
    currency: "USD",
    description: "Rent received from warehouse lease",
    label: "Rental income",
    rowId: "row-003",
  },
  {
    account: "4110",
    amount: 140,
    currency: "USD",
    description: "Lease receipts from equipment rental",
    label: "Lease income",
    rowId: "row-004",
  },
  {
    account: "4200",
    amount: 310,
    currency: "USD",
    description: "Management service fee revenue",
    label: "Service income",
    rowId: "row-005",
  },
  {
    account: "4210",
    amount: 180,
    currency: "USD",
    description: "Consulting service revenue",
    label: "Consulting revenue",
    rowId: "row-006",
  },
  {
    account: "5000",
    amount: -25,
    currency: "USD",
    description: "Monthly bank fees",
    label: "Bank charges",
    rowId: "row-007",
  },
  {
    account: "5100",
    amount: -90,
    currency: "USD",
    description: "Accounting and legal advisory fees",
    label: "Professional fees",
    rowId: "row-008",
  },
  {
    account: "5200",
    amount: -45,
    currency: "USD",
    description: "General office supplies",
    label: "Office expenses",
    rowId: "row-009",
  },
  {
    account: "5300",
    amount: -70,
    currency: "USD",
    description: "Travel and lodging expenses",
    label: "Travel costs",
    rowId: "row-010",
  },
  {
    account: "6000",
    amount: 75,
    currency: "USD",
    description: "Miscellaneous operating revenue",
    label: "Other revenue",
    rowId: "row-011",
  },
  {
    account: "6100",
    amount: 50,
    currency: "USD",
    description: "Uncategorized miscellaneous income",
    label: "Misc income",
    rowId: "row-012",
  },
  {
    account: "7000",
    amount: 33,
    currency: "USD",
    description: "Manual year-end adjustment",
    label: "Unknown adjustment",
    rowId: "row-013",
  },
  {
    account: "7100",
    amount: -40,
    currency: "USD",
    description: "Interest paid on loan",
    label: "Interest expense",
    rowId: "row-014",
  },
  {
    account: "7200",
    amount: 25,
    currency: "USD",
    description: "FX gain from revaluation",
    label: "Foreign exchange gain",
    rowId: "row-015",
  },
];

export const EXPANDED_MAPPING_PIPELINE_RULES = [
  {
    confidence: 0.95,
    description: "Maps interest revenue rows to Z / interest.",
    keywords: ["interest income", "bank interest revenue", "interest earned"],
    matchMode: "contains",
    priority: 10,
    ruleId: "rule-001",
    sectionId: "Z",
    subsectionId: "interest",
    target: "interest_income",
  },
  {
    confidence: 0.92,
    description: "Maps rental and lease income rows to Z / rental.",
    keywords: [
      "rental income",
      "rent received",
      "lease income",
      "lease receipts",
    ],
    matchMode: "contains",
    priority: 10,
    ruleId: "rule-002",
    sectionId: "Z",
    subsectionId: "rental",
    target: "rental_income",
  },
  {
    confidence: 0.9,
    description: "Maps service and consulting revenue rows to Z / services.",
    keywords: [
      "service income",
      "service fee",
      "management service",
      "consulting revenue",
    ],
    matchMode: "contains",
    priority: 9,
    ruleId: "rule-003",
    sectionId: "Z",
    subsectionId: "services",
    target: "service_income",
  },
  {
    confidence: 0.72,
    description:
      "Maps other income rows to Z / other income with lower confidence.",
    keywords: ["other revenue", "misc income", "miscellaneous income"],
    matchMode: "contains",
    priority: 5,
    ruleId: "rule-004",
    sectionId: "Z",
    subsectionId: "other_income",
    target: "other_income",
  },
  {
    confidence: 0.83,
    description: "Maps foreign exchange gains to Z / FX.",
    keywords: ["foreign exchange gain", "fx gain"],
    matchMode: "contains",
    priority: 8,
    ruleId: "rule-005",
    sectionId: "Z",
    subsectionId: "fx",
    target: "fx_gain",
  },
  {
    confidence: 0.9,
    description: "Maps bank fees to W / bank fees.",
    keywords: ["bank charges", "bank fees", "monthly bank fees"],
    matchMode: "contains",
    priority: 10,
    ruleId: "rule-006",
    sectionId: "W",
    subsectionId: "bank_fees",
    target: "bank_fees",
  },
  {
    confidence: 0.9,
    description: "Maps professional fees to W / professional fees.",
    keywords: [
      "professional fees",
      "accounting fees",
      "legal advisory",
      "legal fees",
    ],
    matchMode: "contains",
    priority: 10,
    ruleId: "rule-007",
    sectionId: "W",
    subsectionId: "professional_fees",
    target: "professional_fees",
  },
  {
    confidence: 0.86,
    description: "Maps office expenses to W / office.",
    keywords: ["office expenses", "office supplies", "general office"],
    matchMode: "contains",
    priority: 8,
    ruleId: "rule-008",
    sectionId: "W",
    subsectionId: "office",
    target: "office_expenses",
  },
  {
    confidence: 0.85,
    description: "Maps travel costs to W / travel.",
    keywords: ["travel costs", "travel and lodging", "lodging expenses"],
    matchMode: "contains",
    priority: 8,
    ruleId: "rule-009",
    sectionId: "W",
    subsectionId: "travel",
    target: "travel_expenses",
  },
  {
    confidence: 0.88,
    description: "Maps interest expense to W / interest expense.",
    keywords: ["interest expense", "interest paid"],
    matchMode: "contains",
    priority: 9,
    ruleId: "rule-010",
    sectionId: "W",
    subsectionId: "interest_expense",
    target: "interest_expense",
  },
];

export const EXPANDED_MAPPING_PIPELINE_BLOCK_SPECS = [
  {
    catalogId: "source:excel-workbook",
    config: {
      outputs: "rows",
      rows: EXPANDED_MAPPING_PIPELINE_ROWS,
      sourceKind: "excel_template_mock",
      sourceLocator: "excel-template-mock://expanded-mapping/rows",
      toolId: "source.manual_table",
    },
    description:
      "Immutable Excel-like Source rows for the expanded generic mapping demo.",
    id: "expanded-source-excel-rows",
    label: "Expanded Excel Rows",
    position: { x: -100, y: 90 },
  },
  {
    catalogId: "source:keyword-rules",
    config: {
      keywordRules: EXPANDED_MAPPING_PIPELINE_RULES,
      outputs: "keyword_rules",
      sourceKind: "keyword_rules",
      sourceLocator: "manual-source://expanded-mapping-rules",
      toolId: "source.keyword_rules",
    },
    description:
      "Immutable Rule / Knowledge Source for the expanded generic mapping demo.",
    id: "expanded-source-mapping-rules",
    label: "Expanded Mapping Rules",
    position: { x: -100, y: 360 },
  },
  {
    catalogId: "logic:classification-mapping",
    config: {
      conflictStrategy: "highest_confidence",
      inputs: "data_rows, keyword_rules",
      lowConfidenceThreshold: 0.75,
      matchFields: ["label", "description"],
      matchMode: "contains",
      outputs:
        "mapped_rows, unmatched_rows, low_confidence_rows, conflicts, mapping_summary",
      toolId: "logic.keyword_mapper",
      unmatchedStrategy: "send_to_review",
    },
    description:
      "Reusable Logic tool that classifies source rows using connected mapping rules.",
    id: "expanded-logic-keyword-mapper",
    label: "Keyword Mapper",
    position: { x: 260, y: 220 },
  },
  {
    catalogId: "logic:aggregation",
    config: {
      aggregationMethod: "sum",
      amountField: "amount",
      includeSectionIds: ["Z"],
      inputs: "mapped_rows",
      outputs: "subtotal, included_rows, excluded_rows, aggregation_summary",
      toolId: "logic.aggregation",
    },
    description:
      "Aggregates mapped Z section rows into the protected Z candidate.",
    id: "expanded-logic-aggregate-z",
    label: "Aggregate Z Sections",
    position: { x: 620, y: 80 },
  },
  {
    catalogId: "logic:aggregation",
    config: {
      aggregationMethod: "sum",
      amountField: "amount",
      includeSectionIds: ["W"],
      inputs: "mapped_rows",
      outputs: "subtotal, included_rows, excluded_rows, aggregation_summary",
      toolId: "logic.aggregation",
    },
    description:
      "Aggregates mapped W section rows into the protected W candidate.",
    id: "expanded-logic-aggregate-w",
    label: "Aggregate W Sections",
    position: { x: 620, y: 360 },
  },
  {
    catalogId: "review:low-confidence-warning",
    config: {
      blocking: false,
      inputs: "checked_items",
      outputs: "validation_result, low_confidence_rows",
      threshold: 0.75,
      toolId: "review.confidence_check",
    },
    description:
      "Review / Validation check that warns when mapped rows fall below confidence threshold.",
    id: "expanded-review-mapping-quality",
    label: "Mapping Quality Check",
    position: { x: 620, y: 630 },
  },
  {
    catalogId: "review:unmatched-rows-check",
    config: {
      inputs: "checked_items",
      outputs: "review_status, unmatched_rows",
      toolId: "review.unmatched_rows_check",
    },
    description:
      "Review / Validation check that flags rows not matched by any rule.",
    id: "expanded-review-unmatched-rows",
    label: "Unmatched Rows Check",
    position: { x: 620, y: 830 },
  },
  {
    catalogId: "review:approval-gate",
    config: {
      approved: true,
      inputs: "value_to_approve, validation_result, review_findings",
      notes: "Approved Z for expanded demo despite review warnings.",
      outputs: "approval_status",
      reviewer: "demo-reviewer",
      toolId: "review.approval_gate",
    },
    description:
      "Local mock approval that permits the Z subtotal to become governed.",
    id: "expanded-review-approval-z",
    label: "Approval Gate Z",
    position: { x: 980, y: 150 },
  },
  {
    catalogId: "review:approval-gate",
    config: {
      approved: true,
      inputs: "value_to_approve, validation_result, review_findings",
      notes: "Approved W for expanded demo despite review warnings.",
      outputs: "approval_status",
      reviewer: "demo-reviewer",
      toolId: "review.approval_gate",
    },
    description:
      "Local mock approval that permits the W subtotal to become governed.",
    id: "expanded-review-approval-w",
    label: "Approval Gate W",
    position: { x: 980, y: 430 },
  },
  {
    catalogId: "protected:protected-result",
    config: {
      inputs: "candidate_value, approval_status",
      outputs: "protected_result",
      resultName: "Z",
      runtimeLocked: true,
      toolId: "protected.protected_result",
    },
    description: "Governed final Z result for the expanded mapping demo.",
    id: "expanded-protected-result-z",
    label: "Protected Result Z",
    position: { x: 1340, y: 150 },
  },
  {
    catalogId: "protected:protected-result",
    config: {
      inputs: "candidate_value, approval_status",
      outputs: "protected_result",
      resultName: "W",
      runtimeLocked: true,
      toolId: "protected.protected_result",
    },
    description: "Governed final W result for the expanded mapping demo.",
    id: "expanded-protected-result-w",
    label: "Protected Result W",
    position: { x: 1340, y: 430 },
  },
  {
    catalogId: "output:evidence-pack",
    config: {
      inputs:
        "protected_result, mapped_rows, unmatched_rows, low_confidence_rows, validation_result",
      outputs: "preview",
      toolId: "output.evidence_pack_preview",
    },
    description:
      "Human-readable evidence preview showing Z, W, mappings, warnings, and trace.",
    id: "expanded-output-evidence-preview",
    label: "Z/W Evidence Preview",
    position: { x: 1700, y: 220 },
  },
  {
    catalogId: "output:canonical-json",
    config: {
      inputs:
        "protected_result, mapped_rows, unmatched_rows, low_confidence_rows, validation_result",
      outputs: "canonical_json",
      toolId: "output.canonical_json",
    },
    description:
      "Structured local JSON package for protected Z/W results and trace.",
    id: "expanded-output-canonical-json",
    label: "Z/W Canonical JSON",
    position: { x: 1700, y: 500 },
  },
];

export const EXPANDED_MAPPING_PIPELINE_EDGE_SPECS = [
  {
    bindingLabel: "Rows to classify",
    reason: "Keyword Mapper needs expanded Excel rows.",
    relationshipType: "provides_data_to",
    sourceBlockId: "expanded-source-excel-rows",
    sourceOutputRole: "rows",
    targetBlockId: "expanded-logic-keyword-mapper",
    targetInputRole: "data_rows",
  },
  {
    bindingLabel: "Rules used for classification",
    reason: "Keyword Mapper applies immutable mapping rules.",
    relationshipType: "referenced_by",
    sourceBlockId: "expanded-source-mapping-rules",
    sourceOutputRole: "keyword_rules",
    targetBlockId: "expanded-logic-keyword-mapper",
    targetInputRole: "keyword_rules",
  },
  {
    bindingLabel: "Mapped rows to aggregate for Z",
    reason: "Aggregate Z Sections sums mapped rows with section Z.",
    relationshipType: "transforms_into",
    sourceBlockId: "expanded-logic-keyword-mapper",
    sourceOutputRole: "mapped_rows",
    targetBlockId: "expanded-logic-aggregate-z",
    targetInputRole: "mapped_rows",
  },
  {
    bindingLabel: "Mapped rows to aggregate for W",
    reason: "Aggregate W Sections sums mapped rows with section W.",
    relationshipType: "transforms_into",
    sourceBlockId: "expanded-logic-keyword-mapper",
    sourceOutputRole: "mapped_rows",
    targetBlockId: "expanded-logic-aggregate-w",
    targetInputRole: "mapped_rows",
  },
  {
    bindingLabel: "Mapped rows to validate",
    reason: "Mapping Quality Check reviews row confidence.",
    relationshipType: "triggers_validation",
    sourceBlockId: "expanded-logic-keyword-mapper",
    sourceOutputRole: "mapped_rows",
    targetBlockId: "expanded-review-mapping-quality",
    targetInputRole: "checked_items",
  },
  {
    bindingLabel: "Unmatched rows to review",
    reason: "Unmatched Rows Check reviews rows that could not be classified.",
    relationshipType: "triggers_validation",
    sourceBlockId: "expanded-logic-keyword-mapper",
    sourceOutputRole: "unmatched_rows",
    targetBlockId: "expanded-review-unmatched-rows",
    targetInputRole: "checked_items",
  },
  {
    bindingLabel: "Candidate Z subtotal",
    reason: "Approval Gate Z reviews the candidate Z value.",
    relationshipType: "triggers_validation",
    sourceBlockId: "expanded-logic-aggregate-z",
    sourceOutputRole: "subtotal",
    targetBlockId: "expanded-review-approval-z",
    targetInputRole: "value_to_approve",
  },
  {
    bindingLabel: "Candidate W subtotal",
    reason: "Approval Gate W reviews the candidate W value.",
    relationshipType: "triggers_validation",
    sourceBlockId: "expanded-logic-aggregate-w",
    sourceOutputRole: "subtotal",
    targetBlockId: "expanded-review-approval-w",
    targetInputRole: "value_to_approve",
  },
  {
    bindingLabel: "Confidence warnings for Z approval",
    reason: "Approval Gate Z records mapping quality context.",
    relationshipType: "depends_on",
    sourceBlockId: "expanded-review-mapping-quality",
    sourceOutputRole: "validation_result",
    targetBlockId: "expanded-review-approval-z",
    targetInputRole: "validation_result",
  },
  {
    bindingLabel: "Unmatched row findings for Z approval",
    reason: "Approval Gate Z records unmatched row context.",
    relationshipType: "depends_on",
    sourceBlockId: "expanded-review-unmatched-rows",
    sourceOutputRole: "unmatched_rows",
    targetBlockId: "expanded-review-approval-z",
    targetInputRole: "review_findings",
  },
  {
    bindingLabel: "Confidence warnings for W approval",
    reason: "Approval Gate W records mapping quality context.",
    relationshipType: "depends_on",
    sourceBlockId: "expanded-review-mapping-quality",
    sourceOutputRole: "validation_result",
    targetBlockId: "expanded-review-approval-w",
    targetInputRole: "validation_result",
  },
  {
    bindingLabel: "Unmatched row findings for W approval",
    reason: "Approval Gate W records unmatched row context.",
    relationshipType: "depends_on",
    sourceBlockId: "expanded-review-unmatched-rows",
    sourceOutputRole: "unmatched_rows",
    targetBlockId: "expanded-review-approval-w",
    targetInputRole: "review_findings",
  },
  {
    bindingLabel: "Candidate Z value",
    reason: "Z subtotal becomes the candidate value for Protected Result Z.",
    relationshipType: "feeds_protected_result",
    sourceBlockId: "expanded-logic-aggregate-z",
    sourceOutputRole: "subtotal",
    targetBlockId: "expanded-protected-result-z",
    targetInputRole: "candidate_value",
  },
  {
    bindingLabel: "Approval for Z",
    reason: "Approval Gate Z determines whether Z can lock.",
    relationshipType: "approves_for",
    sourceBlockId: "expanded-review-approval-z",
    sourceOutputRole: "approval_status",
    targetBlockId: "expanded-protected-result-z",
    targetInputRole: "approval_status",
  },
  {
    bindingLabel: "Candidate W value",
    reason: "W subtotal becomes the candidate value for Protected Result W.",
    relationshipType: "feeds_protected_result",
    sourceBlockId: "expanded-logic-aggregate-w",
    sourceOutputRole: "subtotal",
    targetBlockId: "expanded-protected-result-w",
    targetInputRole: "candidate_value",
  },
  {
    bindingLabel: "Approval for W",
    reason: "Approval Gate W determines whether W can lock.",
    relationshipType: "approves_for",
    sourceBlockId: "expanded-review-approval-w",
    sourceOutputRole: "approval_status",
    targetBlockId: "expanded-protected-result-w",
    targetInputRole: "approval_status",
  },
  {
    bindingLabel: "Final Z result",
    reason: "Evidence Preview displays Protected Result Z.",
    relationshipType: "maps_to_output",
    sourceBlockId: "expanded-protected-result-z",
    sourceOutputRole: "protected_result",
    targetBlockId: "expanded-output-evidence-preview",
    targetInputRole: "protected_result",
  },
  {
    bindingLabel: "Final W result",
    reason: "Evidence Preview displays Protected Result W.",
    relationshipType: "maps_to_output",
    sourceBlockId: "expanded-protected-result-w",
    sourceOutputRole: "protected_result",
    targetBlockId: "expanded-output-evidence-preview",
    targetInputRole: "protected_result",
  },
  {
    bindingLabel: "Mapped row details",
    reason: "Evidence Preview lists classified rows.",
    relationshipType: "included_in_output_preview",
    sourceBlockId: "expanded-logic-keyword-mapper",
    sourceOutputRole: "mapped_rows",
    targetBlockId: "expanded-output-evidence-preview",
    targetInputRole: "mapped_rows",
  },
  {
    bindingLabel: "Mapping warnings",
    reason: "Evidence Preview includes low-confidence rows.",
    relationshipType: "included_in_output_preview",
    sourceBlockId: "expanded-review-mapping-quality",
    sourceOutputRole: "low_confidence_rows",
    targetBlockId: "expanded-output-evidence-preview",
    targetInputRole: "review_findings",
  },
  {
    bindingLabel: "Unmatched row warning",
    reason: "Evidence Preview includes unmatched rows.",
    relationshipType: "included_in_output_preview",
    sourceBlockId: "expanded-review-unmatched-rows",
    sourceOutputRole: "unmatched_rows",
    targetBlockId: "expanded-output-evidence-preview",
    targetInputRole: "review_findings",
  },
  {
    bindingLabel: "Final Z JSON",
    reason: "Canonical JSON includes Protected Result Z.",
    relationshipType: "maps_to_output",
    sourceBlockId: "expanded-protected-result-z",
    sourceOutputRole: "protected_result",
    targetBlockId: "expanded-output-canonical-json",
    targetInputRole: "protected_result",
  },
  {
    bindingLabel: "Final W JSON",
    reason: "Canonical JSON includes Protected Result W.",
    relationshipType: "maps_to_output",
    sourceBlockId: "expanded-protected-result-w",
    sourceOutputRole: "protected_result",
    targetBlockId: "expanded-output-canonical-json",
    targetInputRole: "protected_result",
  },
  {
    bindingLabel: "Mapped rows JSON",
    reason: "Canonical JSON includes mapping summary and mapped rows.",
    relationshipType: "included_in_handoff",
    sourceBlockId: "expanded-logic-keyword-mapper",
    sourceOutputRole: "mapped_rows",
    targetBlockId: "expanded-output-canonical-json",
    targetInputRole: "mapped_rows",
  },
  {
    bindingLabel: "Confidence warnings JSON",
    reason: "Canonical JSON includes mapping quality warnings.",
    relationshipType: "included_in_handoff",
    sourceBlockId: "expanded-review-mapping-quality",
    sourceOutputRole: "low_confidence_rows",
    targetBlockId: "expanded-output-canonical-json",
    targetInputRole: "review_findings",
  },
  {
    bindingLabel: "Unmatched warnings JSON",
    reason: "Canonical JSON includes unmatched row warnings.",
    relationshipType: "included_in_handoff",
    sourceBlockId: "expanded-review-unmatched-rows",
    sourceOutputRole: "unmatched_rows",
    targetBlockId: "expanded-output-canonical-json",
    targetInputRole: "review_findings",
  },
];
