import { test, expect } from './workflow-audit-isolation';

test('production individual block tests show real inputs and outputs without becoming full workflow runs', async ({ page }, info) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const start = Date.now();
  await page.goto('/w/pf-document-calculator');
  await page.getByRole('button', { name: 'Build', exact: true }).click();
  await page.getByRole('button', { name: 'Calculate', exact: true }).click();
  await page.getByRole('button', { name: 'Test block', exact: true }).click();
  const panel = page.getByRole('region', { name: 'Individual block test' });
  await panel.getByLabel('Test value 1 number').fill('125.5');
  const runStart = Date.now();
  await panel.getByRole('button', { name: 'Run block', exact: true }).click();
  await expect(panel.getByText('251', { exact: true })).toBeVisible();
  await expect(panel.getByText('125.5', { exact: true })).toBeVisible();
  await expect(panel).toContainText('Individual block test');
  const runMs = Date.now() - runStart;
  await page.screenshot({ path: info.outputPath('production-individual-block.png'), fullPage: true });
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('button', { name: 'Run', exact: true }).first().click();
  await expect(page.getByRole('region', { name: 'Final workflow results' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Build', exact: true }).click();
  await page.getByRole('button', { name: 'Final result', exact: true }).click();
  await page.getByRole('button', { name: 'Test block', exact: true }).click();
  await panel.getByLabel('Block test input source').selectOption('recorded');
  await panel.getByRole('button', { name: 'Run block', exact: true }).click();
  await expect(panel).toContainText('251');
  await expect(panel).not.toContainText('No usable recorded result');
  expect(errors).toEqual([]);
  console.log(JSON.stringify({ scenario: 'individual-block', openMs: runStart - start, runMs, errors }));
});

test('production document-to-output rehearsal uses the UI and survives reload', async ({ page }, info) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  const start = Date.now();
  await page.goto('/w/pf-fapi');
  await page.getByRole('button', { name: 'Build', exact: true }).click();
  const initialBuildMs = Date.now() - start;
  await page.getByText('Test data — upload document or enter examples', { exact: true }).click();
  await page.getByLabel('Upload test document').setInputFiles({ name: 'demo-sales.csv', mimeType: 'text/csv', buffer: Buffer.from('label,amount\nWidget order one,120\nWidget order two,80\nConsulting service,50') });
  await page.getByRole('button', { name: 'Use this test data', exact: true }).click();
  await page.getByRole('button', { name: 'Keyword Mapper', exact: true }).click();
  await page.getByRole('button', { name: 'New', exact: true }).click();
  await page.locator('div.space-y-1\\.5').filter({ has: page.locator('label', { hasText: /^Category ID$/ }) }).locator('input').fill('widget_sales');
  await page.locator('div.space-y-1\\.5').filter({ has: page.locator('label', { hasText: /^Category label$/ }) }).locator('input').fill('Widget sales');
  await page.getByPlaceholder('Add contains keyword').fill('Widget');
  await page.getByPlaceholder('Add contains keyword').press('Enter');
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('button', { name: 'Category Rollup', exact: true }).click();
  await page.getByRole('button', { name: 'New Group', exact: true }).click();
  await page.getByPlaceholder('e.g. income_base').fill('widget_total');
  await page.getByPlaceholder('e.g. Income Base').fill('Widget total');
  await page.getByRole('button', { name: 'Widget sales', exact: true }).click();
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('button', { name: 'FAPI Lines Engine', exact: true }).click();
  await page.getByRole('button', { name: 'New term', exact: true }).click();
  await page.getByPlaceholder('KEY', { exact: true }).fill('WIDGET_RESULT');
  await page.getByPlaceholder('Label', { exact: true }).fill('Adjusted widget sales');
  await page.getByRole('button', { name: /^widget_total(?: = 200)?$/ }).click();
  await page.getByRole('button', { name: '×', exact: true }).click();
  await page.getByRole('spinbutton', { name: 'Number to add' }).fill('500');
  await page.getByRole('button', { name: 'Add number', exact: true }).click();
  await page.getByRole('button', { name: '÷', exact: true }).click();
  await page.getByRole('spinbutton', { name: 'Number to add' }).fill('2');
  await page.getByRole('button', { name: 'Add number', exact: true }).click();
  await page.getByRole('button', { name: 'Test with upstream blocks', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Produced outputs' })).toContainText('50,000');
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('button', { name: 'FAPI Summary Engine', exact: true }).click();
  await page.getByRole('button', { name: 'New term', exact: true }).click();
  await page.getByPlaceholder('KEY', { exact: true }).fill('FINAL_WIDGET_RESULT');
  await page.getByPlaceholder('Label', { exact: true }).fill('Final widget sales');
  await page.getByRole('button', { name: /^WIDGET_RESULT(?: = 50000)?$/ }).click();
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('button', { name: 'Run', exact: true }).first().click();
  await page.getByLabel('Workflow name').fill('Demo rehearsal — widget sales');
  const runStart = Date.now();
  await page.getByRole('button', { name: 'Save changes and run', exact: true }).click();
  await page.locator('summary').filter({ hasText: /^Canonical JSON/ }).click();
  const output = page.locator('details').filter({ has: page.locator('summary', { hasText: /^Canonical JSON/ }) }).first();
  await expect(output).toContainText('50,000');
  const runAndInspectMs = Date.now() - runStart;
  const finalLabel = output.getByText('FINAL WIDGET RESULT', { exact: true }).last();
  await finalLabel.scrollIntoViewIfNeeded();
  await expect(finalLabel).toBeVisible();
  await page.getByRole('region', { name: 'Final workflow results' }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: info.outputPath('production-final-result.png'), fullPage: true });
  await page.reload();
  await page.getByRole('button', { name: 'Workflows', exact: true }).click();
  await page.getByRole('button', { name: 'Demo rehearsal — widget sales', exact: true }).click();
  await page.getByRole('button', { name: 'Run', exact: true }).first().click();
  await page.getByRole('button', { name: 'Run saved version 1', exact: true }).click();
  await page.locator('summary').filter({ hasText: /^Canonical JSON/ }).click();
  await expect(output).toContainText('50,000');
  await expect(page.locator('summary').filter({ hasText: /^Previous runs \(1\)/ })).toBeVisible();
  expect(errors).toEqual([]);
  console.log(JSON.stringify({ initialBuildMs, runAndInspectMs, errors }));
  await info.attach('production-timing', { contentType: 'application/json', body: JSON.stringify({ initialBuildMs, runAndInspectMs, errors }, null, 2) });
});

test('production load of 1000 rows persists two runs and displays the correct total', async ({ page }, info) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/w/pf-fapi');
  await page.getByRole('button', { name: 'Build', exact: true }).click();
  await page.getByText('Test data — upload document or enter examples', { exact: true }).click();
  await page.getByLabel('Upload test document').setInputFiles({ name: 'production-1000.csv', mimeType: 'text/csv', buffer: Buffer.from('label,amount\n' + Array.from({ length: 1000 }, (_, index) => `Interest income ${index + 1},1`).join('\n')) });
  await page.getByRole('button', { name: 'Use this test data', exact: true }).click();
  await page.getByRole('button', { name: 'Run', exact: true }).first().click();
  await page.getByLabel('Workflow name').fill('Production 1000-row rehearsal');
  const start = Date.now();
  await page.getByRole('button', { name: 'Save changes and run', exact: true }).click();
  await page.locator('summary').filter({ hasText: /^Category Rollup/ }).click();
  const rollupOutput = page.locator('details').filter({ has: page.locator('summary', { hasText: /^Category Rollup/ }) }).first();
  const total = rollupOutput.getByText('category Totals', { exact: true }).locator('..').getByText('interest Income', { exact: true }).locator('..');
  await expect(total).toContainText('1,000');
  const runAndInspectMs = Date.now() - start;
  const reopen = async () => {
    await page.reload();
    await page.getByRole('button', { name: 'Workflows', exact: true }).click();
    await page.getByRole('button', { name: 'Production 1000-row rehearsal', exact: true }).click();
    await page.getByRole('button', { name: 'Run', exact: true }).first().click();
  };
  await reopen();
  await page.getByRole('button', { name: 'Run saved version 1', exact: true }).click();
  await reopen();
  await expect(page.locator('summary').filter({ hasText: /^Previous runs \(1\)/ })).toBeVisible();
  await page.locator('summary').filter({ hasText: /^Category Rollup/ }).click();
  await expect(total).toContainText('1,000');
  expect(errors).toEqual([]);
  console.log(JSON.stringify({ count: 1000, runAndInspectMs, persistedRuns: 2, errors }));
  await info.attach('production-load-timing', { contentType: 'application/json', body: JSON.stringify({ count: 1000, runAndInspectMs, persistedRuns: 2, errors }, null, 2) });
});

test('production PDF review calculates final values without downloading document parser bundles', async ({ page }, info) => {
  const errors: string[] = []; const assets: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (request.url().includes('/assets/')) assets.push(request.url()); });
  const start = Date.now();
  await page.goto('/w/pf-document-calculator'); await page.getByRole('button', { name: 'Build', exact: true }).click();
  const openMs = Date.now() - start;
  await page.getByText('Test data — upload document or enter examples', { exact: true }).click();
  const uploadStart = Date.now();
  await page.getByLabel('Upload test document').setInputFiles('e2e/fixtures/demo/sales-check.pdf');
  await expect(page.getByLabel('Row 1 number_1')).toBeVisible({ timeout: 30000 });
  const previewMs = Date.now() - uploadStart;
  await page.getByLabel('Row 1 label', { exact: true }).fill('Item one');
  await page.getByLabel('Row 1 number_1', { exact: true }).fill('120');
  await page.getByLabel('Row 2 label', { exact: true }).fill('Item two');
  await page.getByLabel('Row 2 number_1', { exact: true }).fill('80');
  await page.getByLabel('Remove row 3', { exact: true }).click();
  await page.getByLabel('Number to calculate').selectOption('number_1'); await page.getByLabel('Confirm extracted values').check();
  await page.getByRole('button', { name: 'Use this test data', exact: true }).click();
  await page.getByRole('button', { name: 'Run', exact: true }).first().click();
  await page.getByLabel('Workflow name').fill('Document Calculator — PDF rehearsal');
  const runStart = Date.now();
  await page.getByRole('button', { name: 'Save changes and run', exact: true }).click();
  const summary = page.getByRole('region', { name: 'Final workflow results' });
  await expect(summary).toContainText('400'); await expect(summary).toContainText('units');
  await expect(page.locator('summary').filter({ hasText: /^Final result/ })).toHaveText('Final result \u00b7 success');
  await expect(summary).not.toContainText('review message');
  const runMs = Date.now() - runStart;
  await page.locator('summary').filter({ hasText: /^Final result/ }).click();
  await expect(page.locator('details').filter({ has: page.locator('summary', { hasText: /^Final result/ }) }).first()).toContainText('400');
  await summary.scrollIntoViewIfNeeded();
  await page.screenshot({ path: info.outputPath('neutral-pdf-final-result.png'), fullPage: true });
  expect(errors).toEqual([]);
  expect(assets.filter(url => /\/(spreadsheets|pdf-processing|word-processing)-/.test(url))).toEqual([]);
  console.log(JSON.stringify({ openMs, previewMs, runMs, errors, documentParserDownloads: 0 }));
});
