import type { BlockCatalogItem } from "@/shared/workflow-engine/domain/workflow/block-catalog";

export const BLOCK_CATALOG: BlockCatalogItem[] = [
  {
    id: "trigger:manual",
    family: "Trigger",
    subtype: "Manual / On Demand",
    label: "Manual Trigger",
    description: "Start the workflow manually on demand",
    defaultConfig: {
      fiscalStage: "trigger",
      blockFamily: "Trigger",
      outputs: "triggerPayload",
    },
  },
  {
    id: "trigger:schedule",
    family: "Trigger",
    subtype: "Schedule / Cron",
    label: "Schedule Trigger",
    description: "Fire the workflow on a recurring schedule or cron expression",
    defaultConfig: {
      fiscalStage: "trigger",
      blockFamily: "Trigger",
      schedule: "0 9 * * 1",
      outputs: "triggerPayload",
    },
  },
  {
    id: "trigger:webhook",
    family: "Trigger",
    subtype: "Webhook / API Event",
    label: "Webhook Trigger",
    description: "Fire the workflow when an inbound HTTP event is received",
    defaultConfig: {
      fiscalStage: "trigger",
      blockFamily: "Trigger",
      outputs: "triggerPayload",
    },
  },
  {
    id: "source:manual-entry",
    family: "Source",
    subtype: "Manual Entry",
    label: "Manual Entry",
    description: "Evidence value entered by a builder or reviewer",
    defaultConfig: {
      owner: "Builder",
      inputs: "manual value",
      outputs: "manualEntry",
      rulebookRef: "Manual source values are locked as evidence.",
      sourceLocator: "manual-entry",
      toolId: "source.manual_value",
    },
  },
  {
    id: "source:excel-workbook",
    family: "Source",
    subtype: "Excel / Workbook",
    label: "Excel / Workbook",
    description: "Workbook, worksheet, named range, or tabular evidence",
    defaultConfig: {
      owner: "Tax Operations",
      inputs: "workbook",
      outputs: "workbookRows",
      rulebookRef: "Workbook rows are immutable source evidence.",
      sourceLocator: "workbook://sheet/range",
      toolId: "source.manual_table",
    },
  },
  {
    id: "source:pdf-document",
    family: "Source",
    subtype: "PDF / Document",
    label: "PDF / Document",
    description: "Document, statement, note, schedule, or support package",
    defaultConfig: {
      owner: "Tax Operations",
      inputs: "document",
      outputs: "documentEvidence",
      rulebookRef: "Document facts are referenced, not overwritten.",
      sourceLocator: "document://page/section",
      sourceKind: "pdf_document",
      toolId: "source.pdf_document",
    },
  },
  {
    id: "source:api-http-request",
    family: "Source",
    subtype: "API / HTTP Request",
    label: "API / HTTP Request",
    description: "Live rows fetched from a public JSON API",
    defaultConfig: {
      owner: "Data Operations",
      fieldMap: {},
      inputs: "request",
      maxRows: 250,
      method: "GET",
      outputs: "rows, raw_rows, response_metadata, source_metadata",
      resultsPath: "",
      rulebookRef:
        "The fetched response is pinned into the run, so re-runs replay the exact payload the figures came from.",
      sourceKind: "http_json",
      sourceLocator: "https://api.example.test/reference",
      toolId: "source.http_json",
      url: "",
    },
  },
  {
    id: "source:currency-rate",
    family: "Source",
    subtype: "Currency Rate",
    label: "Bank of Canada FX Rate",
    description: "External FX rate reference for local calculation",
    defaultConfig: {
      documentCurrency: "USD",
      fapiYear: 2025,
      inputs: "Bank of Canada rate lookup",
      outputs: "exchange_rate, rate_metadata",
      overrideRate: 1.35,
      rateProvider: "bank_of_canada",
      rateType: "annual_average",
      reportingCurrency: "CAD",
      rulebookRef:
        "FX rates are captured as source references, then reviewed/protected downstream.",
      sourceKind: "currency_rate",
      sourceLocator: "bank-of-canada://annual-average/USD-CAD",
      toolId: "source.currency_rate",
    },
  },
  {
    id: "source:database-query",
    family: "Source",
    subtype: "Database Query",
    label: "Database Query",
    description: "Read-only query result used as workflow evidence",
    defaultConfig: {
      owner: "Data Operations",
      inputs: "read-only query",
      outputs: "queryRows",
      rulebookRef: "Database source rows are immutable in the builder.",
      sourceLocator: "database://connection/query",
      sourceKind: "database_query",
      toolId: "source.database_query",
    },
  },
  {
    id: "source:web-url",
    family: "Source",
    subtype: "Web / URL",
    label: "Web / URL",
    description: "Reference page or URL captured as evidence",
    defaultConfig: {
      owner: "Research",
      inputs: "url",
      outputs: "webReference",
      rulebookRef: "Web references are captured as source evidence.",
      sourceLocator: "https://example.test/source",
      sourceKind: "web_url",
      toolId: "source.web_url",
    },
  },
  {
    id: "source:ai-search-result",
    family: "Source",
    subtype: "AI Search Result",
    label: "AI Search Result",
    description: "Search result proposed by an AI or agent, then reviewed",
    defaultConfig: {
      owner: "Review",
      inputs: "reviewed search result",
      outputs: "aiSearchEvidence",
      rulebookRef: "AI search results require downstream review.",
      sourceLocator: "proposal://ai-search-result",
      sourceKind: "ai_search",
      toolId: "source.ai_search",
    },
  },
  {
    id: "source:keyword-rules",
    family: "Source",
    subtype: "Keyword Rules",
    label: "Keyword Rulebook",
    description: "Editable keyword-to-category rulebook for mapping review",
    defaultConfig: {
      keywordRules: [
        {
          categoryId: "interest_income",
          categoryLabel: "Interest Income",
          confidence: 0.9,
          keywords: ["interest income", "interest earned", "bank interest"],
          ruleId: "keyword-rule-interest-income",
          suggestedLine: "A",
        },
        {
          categoryId: "rental_income",
          categoryLabel: "Rental Income",
          confidence: 0.9,
          keywords: ["rental income", "rent income", "lease income"],
          ruleId: "keyword-rule-rents",
          suggestedLine: "A",
        },
        {
          categoryId: "bank_fees",
          categoryLabel: "Bank Fees",
          confidence: 0.8,
          keywords: ["bank charges", "office expenses", "general expenses"],
          ruleId: "keyword-rule-general-expenses",
          suggestedLine: "EXPENSES",
        },
        {
          categoryId: "professional_fees",
          categoryLabel: "Professional Fees",
          confidence: 0.8,
          keywords: ["professional fees", "accounting fees", "audit fees"],
          ruleId: "keyword-rule-accounting-expenses",
          suggestedLine: "EXPENSES",
        },
        {
          categoryId: "other_income",
          categoryLabel: "Other Income",
          confidence: 0.7,
          keywords: ["other revenue", "miscellaneous income", "sundry income"],
          ruleId: "keyword-rule-other-fapi-income",
          suggestedLine: "A",
        },
      ],
      owner: "Fiscal Systems",
      inputs: "draft keyword rulebook",
      outputs: "keyword_rules, rule_metadata, rule_version",
      rulebookRef:
        "Keyword rulebooks are editable in draft and versioned after use.",
      sourceKind: "keyword_rules",
      sourceLocator: "manual-source://keyword-rules",
      toolId: "source.keyword_rules",
    },
  },
  {
    id: "source:aggregation-rules",
    family: "Source",
    subtype: "Aggregation Rules",
    label: "Aggregation Rulebook",
    description: "Editable rollup and formula rulebook for calculation review",
    defaultConfig: {
      aggregationRules: [
        {
          children: [],
          description: "Base income rollup from mapped atomic categories.",
          includeCategoryIds: [
            "interest_income",
            "rental_income",
            "service_income",
            "other_income",
          ],
          label: "Income Base",
          nodeId: "income_base",
          nodeType: "group",
          operation: "sum",
          order: 10,
        },
        {
          children: [],
          description: "Base expense rollup from mapped atomic categories.",
          includeCategoryIds: [
            "bank_fees",
            "professional_fees",
            "interest_expense",
          ],
          label: "Expense Base",
          nodeId: "expense_base",
          nodeType: "group",
          operation: "sum",
          order: 20,
        },
        {
          children: [],
          description: "Demonstrates subtracting one rollup from another.",
          label: "Income After Expenses",
          nodeId: "income_after_expenses",
          nodeType: "group",
          operands: [
            { label: "Income Base", refId: "income_base", refType: "node" },
            { label: "Expense Base", refId: "expense_base", refType: "node" },
          ],
          operation: "subtract",
          order: 30,
        },
        {
          children: [],
          description: "Draft adjustment factor used by Result Z.",
          label: "Z Adjustment Factor",
          nodeId: "z_adjustment_factor",
          nodeType: "constant",
          operation: "pass_through",
          order: 40,
          value: 1,
        },
        {
          children: [],
          label: "Result Z",
          nodeId: "Z",
          nodeType: "final_result",
          operands: [
            { label: "Income Base", refId: "income_base", refType: "node" },
            {
              label: "Z Adjustment Factor",
              refId: "z_adjustment_factor",
              refType: "node",
            },
          ],
          operation: "multiply",
          order: 50,
          resultName: "Z",
        },
        {
          children: [],
          label: "Result W",
          nodeId: "W",
          nodeType: "final_result",
          operands: [
            { label: "Expense Base", refId: "expense_base", refType: "node" },
          ],
          operation: "sum",
          order: 60,
          resultName: "W",
        },
        {
          children: [],
          description: "Demonstrates addition of two rollups.",
          label: "Optional Check Total",
          nodeId: "optional_check_total",
          nodeType: "formula",
          operands: [
            { label: "Income Base", refId: "income_base", refType: "node" },
            { label: "Expense Base", refId: "expense_base", refType: "node" },
          ],
          operation: "add",
          order: 70,
        },
      ],
      owner: "Fiscal Systems",
      inputs: "draft aggregation rulebook",
      outputs:
        "aggregation_rules, aggregation_tree, rule_metadata, rule_version",
      rulebookRef:
        "Aggregation rulebooks are editable in draft and versioned after use.",
      sourceKind: "aggregation_rules",
      sourceLocator: "manual-source://aggregation-rules",
      toolId: "source.aggregation_rules",
    },
  },
  {
    id: "source:rollup-rules",
    family: "Source",
    subtype: "Rollup Rules",
    label: "Rollup Rules Source",
    description: "Editable rulebook for grouping mapped categories into totals",
    defaultConfig: {
      owner: "Fiscal Systems",
      inputs: "draft rollup rulebook",
      outputs: "rollup_rules, rule_metadata, rule_version",
      rollupRules: [
        {
          description: "Adds income mapped categories.",
          includeCategoryIds: [
            "interestIncome",
            "rents",
            "royalties",
            "dividends",
            "otherFapiIncome",
          ],
          label: "Income Bucket",
          operation: "sum",
          rollupId: "income_bucket",
        },
        {
          description: "Adds expenses using absolute values.",
          includeCategoryIds: [
            "generalExpenses",
            "legalExpenses",
            "accountingExpenses",
          ],
          label: "Expense Bucket",
          operation: "sum_abs",
          rollupId: "expense_bucket",
        },
      ],
      rulebookRef:
        "Rollup rulebooks group mapped categories without owning final formulas.",
      sourceKind: "rollup_rules",
      sourceLocator: "manual-source://rollup-rules",
      toolId: "source.rollup_rules",
    },
  },
  {
    id: "source:calculation-rules",
    family: "Source",
    subtype: "Calculation Rules",
    label: "Calculation Rules Source",
    description:
      "Editable formula rules over named rollup and protected inputs",
    defaultConfig: {
      calculationRules: [
        {
          calculationId: "A",
          description: "A = max(income_bucket - expense_bucket, 0)",
          label: "A",
          operands: ["income_bucket", "expense_bucket"],
          operation: "max_subtract_zero",
          resultKey: "A",
        },
        {
          calculationId: "GROSS",
          description: "Gross = A + A1 + A2 + B + C",
          label: "Gross",
          operands: ["A", "A1", "A2", "B", "C"],
          operation: "add",
          resultKey: "GROSS",
        },
        {
          calculationId: "DEDUCTIONS",
          description: "Deductions = D + E + F + F1 + G + H",
          label: "Deductions",
          operands: ["D", "E", "F", "F1", "G", "H"],
          operation: "add",
          resultKey: "DEDUCTIONS",
        },
        {
          calculationId: "FAPI_BRUT",
          description: "FAPI Brut = max(GROSS - DEDUCTIONS, 0)",
          label: "FAPI Brut",
          operands: ["GROSS", "DEDUCTIONS"],
          operation: "max_subtract_zero",
          resultKey: "FAPI_BRUT",
        },
        {
          calculationId: "FAT_DEDUCTION",
          description: "FAT Deduction = min(max(FAT_PAID, 0) * RTF, FAPI_BRUT)",
          label: "FAT Deduction",
          operands: ["FAT_PAID", "RTF", "FAPI_BRUT"],
          operation: "min_multiply_cap",
          resultKey: "FAT_DEDUCTION",
        },
        {
          calculationId: "NET_FAPI",
          description: "Net FAPI = max(FAPI_BRUT - FAT_DEDUCTION, 0)",
          label: "Net FAPI",
          operands: ["FAPI_BRUT", "FAT_DEDUCTION"],
          operation: "max_subtract_zero",
          resultKey: "NET_FAPI",
        },
        {
          calculationId: "NET_FAPI_CAD",
          description: "Net FAPI CAD = NET_FAPI * FX_RATE",
          label: "Net FAPI CAD",
          operands: ["NET_FAPI", "FX_RATE"],
          operation: "multiply",
          resultKey: "NET_FAPI_CAD",
        },
      ],
      owner: "Fiscal Systems",
      inputs: "draft calculation rulebook",
      outputs: "calculation_rules, rule_metadata, rule_version",
      rulebookRef:
        "Calculation rulebooks define formulas over named values without changing Sources.",
      sourceKind: "calculation_rules",
      sourceLocator: "manual-source://calculation-rules",
      toolId: "source.calculation_rules",
    },
  },
  {
    id: "logic:hierarchy-aggregator",
    family: "Logic",
    subtype: "Hierarchy Aggregator",
    label: "Rollup & Calculation Engine",
    description:
      "Roll up mapped categories and calculate formula/final result nodes",
    defaultConfig: {
      owner: "Fiscal Systems",
      inputs: "mapped_rows, aggregation_rules",
      operation: "sum",
      outputs:
        "category_totals, node_totals, group_totals, final_totals, aggregation_tree, formula_trace",
      rulebookRef:
        "Rollup & Calculation Engine applies Source aggregation rules without mutating source rows.",
      toolGroup: "calculation",
      toolId: "logic.hierarchy_aggregator",
    },
  },
  {
    id: "logic:category-rollup-aggregator",
    family: "Logic",
    subtype: "Category Rollup Aggregator",
    label: "Category Rollup Aggregator",
    description: "Group mapped rows into category and rollup totals",
    defaultConfig: {
      owner: "Fiscal Systems",
      inputs: "mapped_rows, rollup_rules",
      outputs:
        "category_totals, rollup_totals, named_values, included_rows_by_category, included_rows_by_rollup, excluded_rows, rollup_formula_trace, rollup_summary",
      rulebookRef:
        "Category Rollup Aggregator only groups and sums mapped rows.",
      toolGroup: "calculation",
      toolId: "logic.category_rollup_aggregator",
    },
  },
  {
    id: "logic:calculation-engine",
    family: "Logic",
    subtype: "Calculation Engine",
    label: "Calculation Engine",
    description: "Apply formula rules to named values and protected inputs",
    defaultConfig: {
      owner: "Fiscal Systems",
      inputs: "named_values, protected_inputs",
      outputs:
        "calculated_results, formula_trace, calculation_summary, named_values",
      rulebookRef:
        "Calculation Engine evaluates formulas without grouping source rows.",
      toolGroup: "calculation",
      toolId: "logic.calculation_engine",
      mode: "auto",
      outputCurrency: "USD",
      rounding: { moneyDecimals: 2 },
      formulas: [
        {
          calculationId: "A",
          label: "A",
          operation: "max_subtract_zero",
          operands: ["income_bucket", "expense_bucket"],
          resultKey: "A",
          description: "A = max(income_bucket - expense_bucket, 0)",
        },
        {
          calculationId: "A1",
          label: "A1",
          operation: "multiply",
          operands: ["debtForgiveness", 2],
          resultKey: "A1",
          description: "A1 = debtForgiveness * 2",
        },
        {
          calculationId: "A2",
          label: "A2",
          operation: "pass_through",
          operands: ["priorYearG"],
          resultKey: "A2",
          description: "A2 = priorYearG",
        },
        {
          calculationId: "B",
          label: "B",
          operation: "multiply",
          operands: ["capGains", "inclusionRate"],
          resultKey: "B",
          description: "B = capGains * inclusionRate",
        },
        {
          calculationId: "C",
          label: "C",
          operation: "pass_through",
          operands: ["cfaIncome"],
          resultKey: "C",
          description: "C = cfaIncome",
        },
        {
          calculationId: "D",
          label: "D",
          operation: "pass_through",
          operands: ["businessLosses"],
          resultKey: "D",
          description: "D = businessLosses",
        },
        {
          calculationId: "E",
          label: "E",
          operation: "pass_through",
          operands: ["faclCarryforward"],
          resultKey: "E",
          description: "E = faclCarryforward",
        },
        {
          calculationId: "F",
          label: "F",
          operation: "pass_through",
          operands: ["prescribedAmount"],
          resultKey: "F",
          description: "F = prescribedAmount",
        },
        {
          calculationId: "F1",
          label: "F1",
          operation: "pass_through",
          operands: ["prescribedAmountF1"],
          resultKey: "F1",
          description: "F1 = prescribedAmountF1",
        },
        {
          calculationId: "G",
          label: "G",
          operation: "pass_through",
          operands: ["dividendDeductions"],
          resultKey: "G",
          description: "G = dividendDeductions",
        },
        {
          calculationId: "H",
          label: "H",
          operation: "pass_through",
          operands: ["partnershipDividends"],
          resultKey: "H",
          description: "H = partnershipDividends",
        },
        {
          calculationId: "FAT_PAID",
          label: "FAT Paid",
          operation: "pass_through",
          operands: ["fatPaid"],
          resultKey: "FAT_PAID",
          description: "FAT_PAID = fatPaid",
        },
        {
          calculationId: "RTF",
          label: "RTF",
          operation: "pass_through",
          operands: ["rtf"],
          resultKey: "RTF",
          description: "RTF = rtf",
        },
        {
          calculationId: "FX_RATE",
          label: "FX Rate",
          operation: "pass_through",
          operands: ["fxRate"],
          resultKey: "FX_RATE",
          description: "FX_RATE = fxRate",
        },
        {
          calculationId: "GROSS",
          label: "Gross",
          operation: "add",
          operands: ["A", "A1", "A2", "B", "C"],
          resultKey: "GROSS",
          description: "Gross = A + A1 + A2 + B + C",
        },
        {
          calculationId: "DEDUCTIONS",
          label: "Deductions",
          operation: "add",
          operands: ["D", "E", "F", "F1", "G", "H"],
          resultKey: "DEDUCTIONS",
          description: "Deductions = D + E + F + F1 + G + H",
        },
        {
          calculationId: "FAPI_BRUT",
          label: "FAPI Brut",
          operation: "max_subtract_zero",
          operands: ["GROSS", "DEDUCTIONS"],
          resultKey: "FAPI_BRUT",
          description: "FAPI Brut = max(GROSS - DEDUCTIONS, 0)",
        },
        {
          calculationId: "FAT_DEDUCTION",
          label: "FAT Deduction",
          operation: "min_multiply_cap",
          operands: ["FAT_PAID", "RTF", "FAPI_BRUT"],
          resultKey: "FAT_DEDUCTION",
          description: "FAT Deduction = min(max(FAT_PAID, 0) * RTF, FAPI_BRUT)",
        },
        {
          calculationId: "NET_FAPI",
          label: "Net FAPI",
          operation: "max_subtract_zero",
          operands: ["FAPI_BRUT", "FAT_DEDUCTION"],
          resultKey: "NET_FAPI",
          description: "Net FAPI = max(FAPI_BRUT - FAT_DEDUCTION, 0)",
        },
        {
          calculationId: "NET_FAPI_CAD",
          label: "Net FAPI CAD",
          operation: "multiply",
          operands: ["NET_FAPI", "FX_RATE"],
          resultKey: "NET_FAPI_CAD",
          description: "Net FAPI CAD = NET_FAPI * FX_RATE",
        },
      ],
    },
  },
  {
    id: "logic:classification-mapping",
    family: "Logic",
    subtype: "Classification / Mapping",
    label: "Classification / Mapping",
    description: "Classify rows or map source values to canonical fields",
    defaultConfig: {
      owner: "Fiscal Systems",
      inputs: "source rows",
      outputs: "mappedRows",
      rulebookRef: "Mappings are downstream annotations, not source edits.",
      toolGroup: "mapping",
      toolId: "logic.keyword_mapper",
    },
  },
  // ── Review / Validation ────────────────────────────────────────────────────
  // These gates already had working executors in the tool registry but no palette
  // entry, so they could not be placed on a canvas. Catalog ids added here to make
  // the governance layer buildable (subtypes resolve via REVIEW_TOOL_BY_SUBTYPE).
  {
    id: "review:unmatched-rows-check",
    family: "Review / Validation",
    subtype: "Unmatched Rows Check",
    label: "Unmatched Rows Check",
    description: "Flags rows the classifier could not categorise",
    defaultConfig: {
      inputs: "mapped_rows, unmatched_rows",
      outputs: "review_status, unmatched_rows",
      owner: "Review",
      rulebookRef: "Unclassified rows must be resolved or explicitly excluded.",
      toolId: "review.unmatched_rows_check",
    },
  },
  {
    id: "review:low-confidence-warning",
    family: "Review / Validation",
    subtype: "Low Confidence Warning",
    label: "Low Confidence Warning",
    description: "Surfaces weak keyword matches for a human to confirm",
    defaultConfig: {
      confidenceThreshold: 0.75,
      inputs: "mapped_rows",
      outputs: "review_status, low_confidence_rows",
      owner: "Review",
      rulebookRef: "Matches below the confidence threshold require review.",
      toolId: "review.low_confidence_warning",
    },
  },
  {
    id: "review:approval-gate",
    family: "Review / Validation",
    subtype: "Approval Gate",
    label: "Approval Gate",
    description: "Human sign-off before results are released downstream",
    defaultConfig: {
      inputs: "value_to_approve, validation_result, review_findings",
      outputs: "approval_status, review_status",
      owner: "Review",
      rulebookRef: "Results require explicit approval before handoff.",
      toolId: "review.approval_gate",
    },
  },
  {
    id: "review:output-readiness-check",
    family: "Review / Validation",
    subtype: "Output Readiness Check",
    label: "Output Readiness Check",
    description: "Confirms every governed value is settled before export",
    defaultConfig: {
      inputs: "protected_values, validation_result, review_findings",
      outputs: "validation_result, review_status",
      owner: "Review",
      rulebookRef: "Outputs are gated until all governed values are final.",
      toolId: "review.output_readiness_check",
    },
  },
  {
    id: "field:field-block",
    family: "Field",
    subtype: "Field Block",
    label: "Field Block",
    description: "Display named results and their category breakdowns in the user-facing UI",
    defaultConfig: {
      fields: [],
      toolId: "field.field_block",
    },
  },
  {
    id: "output:csv-export",
    family: "Output",
    subtype: "CSV Export",
    label: "CSV Export",
    description: "Delimited export for downstream review",
    defaultConfig: {
      owner: "Tax Delivery",
      inputs: "approved values",
      outputs: "csv, fileName, columns",
      rulebookRef: "CSV output is generated from approved data.",
      toolId: "output.csv_export",
    },
  },
  {
    id: "output:excel-export",
    family: "Output",
    subtype: "Excel Export",
    label: "Excel Export",
    description: "Workbook output for review or handoff",
    defaultConfig: {
      owner: "Tax Delivery",
      inputs: "approved values",
      outputs: "sheets, workbookSpec, fileName",
      rulebookRef: "Excel output is generated from approved data.",
      toolId: "output.excel_export",
    },
  },
  {
    id: "output:pdf-report",
    family: "Output",
    subtype: "PDF Report",
    label: "PDF Report",
    description: "Review-ready PDF package",
    defaultConfig: {
      owner: "Tax Delivery",
      inputs: "approved values",
      outputs: "pdfReport",
      rulebookRef: "PDF reports are generated from approved values.",
      toolId: "output.pdf_report",
    },
  },
  {
    id: "output:evidence-pack",
    family: "Output",
    subtype: "Evidence Pack",
    label: "Evidence Pack",
    description: "Source references, validations, and approvals bundle",
    defaultConfig: {
      owner: "Tax Delivery",
      inputs: "sources and approvals",
      outputs: "evidencePack",
      rulebookRef: "Evidence packs preserve source support.",
      toolId: "output.evidence_pack_preview",
    },
  },
  {
    id: "output:canonical-json",
    family: "Output",
    subtype: "Canonical JSON",
    label: "Canonical JSON",
    description: "Canonical machine-readable workflow output",
    defaultConfig: {
      owner: "Tax Delivery",
      inputs: "approved graph state",
      outputs: "canonicalJson",
      rulebookRef: "Canonical JSON is a local v1 export artifact.",
      toolId: "output.canonical_json",
    },
  },
  {
    id: "output:taxprep-handoff",
    family: "Output",
    subtype: "Taxprep Handoff",
    label: "Taxprep Handoff",
    description: "Placeholder handoff artifact for Taxprep",
    defaultConfig: {
      owner: "Tax Delivery",
      inputs: "approved values",
      outputs: "taxprepHandoff",
      rulebookRef: "V1 exports a placeholder, not a live integration.",
      toolId: "output.taxprep_handoff",
    },
  },
  {
    id: "output:onesource-handoff",
    family: "Output",
    subtype: "ONESOURCE Handoff",
    label: "ONESOURCE Handoff",
    description: "Placeholder handoff artifact for ONESOURCE",
    defaultConfig: {
      owner: "Tax Delivery",
      inputs: "approved values",
      outputs: "onesourceHandoff",
      rulebookRef: "V1 exports a placeholder, not a live integration.",
      toolId: "output.onesource_handoff",
    },
  },
  {
    id: "ai:ai-search",
    family: "AI / Agent",
    subtype: "AI Search",
    label: "AI Search",
    description: "Proposal-only AI search block",
    defaultConfig: {
      owner: "Builder",
      inputs: "search prompt",
      outputs: "aiSearchProposal",
      rulebookRef: "AI proposals require approval before changing workflow.",
    },
  },
  {
    id: "ai:ai-mapping-suggestion",
    family: "AI / Agent",
    subtype: "AI Mapping Suggestion",
    label: "AI Mapping Suggestion",
    description: "Proposal-only mapping suggestion",
    defaultConfig: {
      owner: "Builder",
      inputs: "source rows",
      outputs: "aiMappingProposal",
      rulebookRef: "AI mapping suggestions do not mutate the workflow.",
    },
  },
  {
    id: "ai:ai-formula-proposal",
    family: "AI / Agent",
    subtype: "AI Formula Proposal",
    label: "AI Formula Proposal",
    description: "Proposal-only formula candidate",
    defaultConfig: {
      owner: "Builder",
      inputs: "calculation prompt",
      outputs: "aiFormulaProposal",
      rulebookRef: "AI formula proposals require approval.",
    },
  },
  {
    id: "ai:ai-workflow-proposal",
    family: "AI / Agent",
    subtype: "AI Workflow Proposal",
    label: "AI Workflow Proposal",
    description: "Proposal-only workflow change package",
    defaultConfig: {
      owner: "Builder",
      inputs: "workflow prompt",
      outputs: "aiWorkflowProposal",
      rulebookRef: "AI workflow proposals stay separate until approved.",
    },
  },

  // ── Blocks that had a working executor but no palette entry ────────────────
  // The 2026-08-12 audit found 16 registered tools unreachable from the palette.
  // The ones below are the load-bearing ones — most importantly BOTH Protected
  // tools, which is the family the whole governance story rests on: you could not
  // place a governed value at all. (The five createMockParserTool stubs are left
  // unreachable on purpose — a mock parser should not be placeable by accident.)
  {
    id: "protected:protected-input",
    family: "Protected",
    subtype: "Protected Input",
    label: "Protected Input",
    description:
      "A governed input value that cannot be edited once locked — corrections are modelled downstream",
    defaultConfig: {
      inputs: "candidate_value, approval_status",
      outputs: "protected_value",
      owner: "Review",
      rulebookRef: "Protected inputs are locked after approval.",
      toolId: "protected.protected_input",
    },
  },
  {
    id: "protected:protected-result",
    family: "Protected",
    subtype: "Protected Result",
    label: "Protected Result",
    description:
      "A governed final figure — the value a deliverable is allowed to state",
    defaultConfig: {
      inputs: "computed_values, approval_status",
      outputs: "protected_result",
      owner: "Review",
      rulebookRef: "Final amounts are governed and require approval.",
      toolId: "protected.protected_result",
    },
  },
  {
    id: "protected:locked-rate",
    family: "Protected",
    subtype: "Locked Rate",
    label: "Locked Rate",
    description:
      "A reviewed rate (e.g. FX) pinned for the engagement so every figure uses the same one",
    defaultConfig: {
      inputs: "candidate_value, approval_status",
      outputs: "protected_value",
      owner: "Review",
      rulebookRef: "Rates are locked after review and reused unchanged.",
      toolId: "protected.protected_input",
    },
  },
  {
    id: "review:required-input-check",
    family: "Review / Validation",
    subtype: "Required Input Check",
    label: "Required Input Check",
    description: "Blocks the run when a required input is missing",
    defaultConfig: {
      inputs: "checked_items",
      outputs: "validation_result",
      owner: "Review",
      rulebookRef: "Required inputs must be present before computation.",
      toolId: "review.required_input_check",
    },
  },
  {
    id: "review:formula-consistency-check",
    family: "Review / Validation",
    subtype: "Formula Consistency Check",
    label: "Formula Consistency Check",
    description: "Verifies computed figures still agree with their formulas",
    defaultConfig: {
      inputs: "computed_values",
      outputs: "validation_result",
      owner: "Review",
      rulebookRef: "Figures must reconcile to their stated formula.",
      toolId: "review.formula_consistency_check",
    },
  },
  {
    id: "review:manual-override-review",
    family: "Review / Validation",
    subtype: "Manual Override Review",
    label: "Manual Override Review",
    description:
      "Surfaces every manual override (including an FX rate) for explicit review",
    defaultConfig: {
      inputs: "candidate_value",
      outputs: "review_findings",
      owner: "Review",
      rulebookRef: "Manual overrides are reviewed, never silent.",
      toolId: "review.fx_rate_review",
    },
  },
];
