import type { ToolDefinition } from "../../../runtime/types";
import { SAMPLE_MANUAL_TABLE_ROWS } from "./fixtures";

export const manualTableDefinition: ToolDefinition = {
  defaultConfig: {
    rows: SAMPLE_MANUAL_TABLE_ROWS,
    sourceKind: "manual_table",
  },
  description: "Reads immutable tabular Source evidence from local config.",
  displayName: "Manual Table Source",
  family: "Source",
  inputRoles: [],
  outputRoles: [
    {
      canRouteToFamilies: ["Logic", "Output"],
      description: "Uploaded workbook file metadata.",
      id: "workbook_file",
      label: "Workbook file",
      outputKey: "workbookFile",
      outputType: "workbook_file",
      samplePreview: "uploaded workbook metadata",
    },
    {
      canRouteToFamilies: ["Logic", "Output"],
      description: "Selected worksheet metadata.",
      id: "selected_sheet",
      label: "Selected sheet",
      outputKey: "selectedSheet",
      outputType: "selected_sheet",
      samplePreview: "selected sheet",
    },
    {
      canRouteToFamilies: ["Logic", "Output"],
      description: "Selected workbook range exposed as Source evidence.",
      id: "selected_range",
      label: "Selected range",
      outputKey: "selectedRange",
      outputType: "selected_range",
      samplePreview: "A1:F16",
    },
    {
      canRouteToFamilies: ["Logic"],
      description: "Immutable source rows with evidence references.",
      id: "rows",
      label: "Rows",
      outputKey: "rows",
      outputType: "rows",
      samplePreview: "5 source rows",
    },
    {
      canRouteToFamilies: ["Logic"],
      description: "Selected immutable source rows exposed downstream.",
      id: "selected_rows",
      label: "Selected rows",
      outputKey: "rows",
      outputType: "table_rows",
      samplePreview: "selected source rows",
    },
    {
      canRouteToFamilies: ["Logic", "Output"],
      description: "Original parsed raw rows before local normalization.",
      id: "raw_rows",
      label: "Raw rows",
      outputKey: "rawRows",
      outputType: "raw_rows",
      samplePreview: "raw uploaded rows",
    },
    {
      canRouteToFamilies: ["Logic", "Output"],
      description: "Local Source file and column metadata.",
      id: "source_metadata",
      label: "Source metadata",
      outputKey: "sourceMetadata",
      outputType: "source_metadata",
      samplePreview: "source metadata",
    },
    {
      canRouteToFamilies: ["Logic", "Output"],
      description: "Local source locator for the selected evidence slice.",
      id: "source_locator",
      label: "Source locator",
      outputKey: "sourceLocator",
      outputType: "source_locator",
      samplePreview: "sheet/range locator",
    },
  ],
  runMode: "local_mock",
  subtype: "Manual Entry",
  toolGroup: "source",
  toolId: "source.manual_table",
};
