import type { ToolDefinition } from "../../../runtime/types";

export const hierarchyAggregatorDefinition: ToolDefinition = {
  defaultConfig: {
    missingReferenceStrategy: "warn_and_zero",
    operation: "sum",
  },
  description:
    "Groups mapped categories into rollups and evaluates calculator/formula nodes to produce final totals.",
  displayName: "Rollup & Calculation Engine",
  family: "Logic",
  inputRoles: [
    {
      acceptedFamilies: ["Logic"],
      acceptedOutputTypes: ["mapped_rows"],
      allowMultiple: true,
      description: "Rows classified by Keyword Mapper.",
      id: "mapped_rows",
      label: "Mapped rows",
      required: true,
    },
    {
      acceptedFamilies: ["Source"],
      acceptedOutputTypes: ["aggregation_rules"],
      acceptedSourceKinds: ["aggregation_rules", "rule_knowledge_source"],
      allowMultiple: true,
      description:
        "Rulebook with rollup, formula, constant, official-line, and final-result nodes.",
      id: "aggregation_rules",
      label: "Aggregation rules",
      required: true,
    },
    {
      acceptedFamilies: ["Source", "Review / Validation", "Protected"],
      acceptedOutputTypes: [
        "exchange_rate",
        "fapi_inputs",
        "governed_value",
        "reviewed_exchange_rate",
      ],
      acceptedSourceKinds: ["currency_rate", "excel_workbook", "fapi_inputs"],
      allowMultiple: true,
      description:
        "Workbook calculation inputs plus reviewed/protected FX assumptions.",
      id: "fapi_inputs",
      label: "FAPI inputs",
      required: false,
    },
  ],
  outputRoles: [
    {
      canRouteToFamilies: ["Output", "Review / Validation"],
      description: "Totals for each mapped category.",
      id: "category_totals",
      label: "Category totals",
      outputKey: "categoryTotals",
      outputType: "category_totals",
      samplePreview: "category totals",
    },
    {
      canRouteToFamilies: ["Output", "Review / Validation"],
      description:
        "Totals for every evaluated rollup, formula, constant, and final-result node.",
      id: "node_totals",
      label: "Rollup / formula node totals",
      outputKey: "nodeTotals",
      outputType: "node_totals",
      samplePreview: "node totals",
    },
    {
      canRouteToFamilies: ["Output", "Review / Validation"],
      description: "Totals for rollup/group hierarchy nodes.",
      id: "group_totals",
      label: "Rollup totals",
      outputKey: "groupTotals",
      outputType: "group_totals",
      samplePreview: "group totals",
    },
    {
      canRouteToFamilies: ["Protected", "Output", "Review / Validation"],
      description: "Named final result totals such as Z and W.",
      id: "final_totals",
      label: "Final totals",
      outputKey: "finalTotals",
      outputType: "final_totals",
      samplePreview: "Z = 765, W = -155",
    },
    {
      canRouteToFamilies: ["Protected", "Output", "Review / Validation"],
      description: "Calculated official line values such as A, A1, and B.",
      id: "official_line_values",
      label: "Official line values",
      outputKey: "officialLineValues",
      outputType: "official_line_values",
      samplePreview: "A = 4950",
    },
    {
      canRouteToFamilies: ["Output"],
      description: "Aggregation hierarchy with computed totals.",
      id: "aggregation_tree",
      label: "Aggregation tree",
      outputKey: "aggregationTree",
      outputType: "aggregation_tree",
    },
    {
      canRouteToFamilies: ["Output", "Review / Validation"],
      description: "Rows included by each hierarchy node.",
      id: "included_rows_by_node",
      label: "Included rows by node",
      outputKey: "includedRowsByNode",
      outputType: "included_rows_by_node",
    },
    {
      canRouteToFamilies: ["Output", "Review / Validation"],
      description: "Mapped rows not included in any final result.",
      id: "excluded_rows",
      label: "Excluded rows",
      outputKey: "excludedRows",
      outputType: "excluded_rows",
    },
    {
      canRouteToFamilies: ["Output", "Protected", "Review / Validation"],
      description: "Readable formulas for each hierarchy node and final total.",
      id: "formula_trace",
      label: "Formula trace",
      outputKey: "formulaTrace",
      outputType: "formula_trace",
    },
    {
      canRouteToFamilies: ["Output", "Review / Validation"],
      description: "Summary counts for the hierarchy aggregation.",
      id: "aggregation_summary",
      label: "Aggregation summary",
      outputKey: "aggregationSummary",
      outputType: "aggregation_summary",
    },
  ],
  runMode: "local_mock",
  subtype: "Hierarchy Aggregator",
  toolGroup: "calculation",
  toolId: "logic.hierarchy_aggregator",
};
