import { SAMPLE_MANUAL_TABLE_ROWS } from "../../source/manual-table/fixtures";
import type { MappedKeywordRow } from "./schema";

export const EXPECTED_KEYWORD_MAPPER_OUTPUT: MappedKeywordRow[] = [
  {
    ...SAMPLE_MANUAL_TABLE_ROWS[0],
    categoryId: "interest_income",
    categoryLabel: "Interest Income",
    confidence: 0.9,
    matchedKeyword: "interest income",
    matchedRuleId: "keyword-rule-interest-income",
    rowSourceTrace: [],
    ruleId: "keyword-rule-interest-income",
    ruleTrace: [],
    ruleSourceTrace: [],
    sourceRow: SAMPLE_MANUAL_TABLE_ROWS[0],
    status: "mapped",
  },
  {
    ...SAMPLE_MANUAL_TABLE_ROWS[1],
    categoryId: "rental_income",
    categoryLabel: "Rental Income",
    confidence: 0.9,
    matchedKeyword: "rental income",
    matchedRuleId: "keyword-rule-rents",
    rowSourceTrace: [],
    ruleId: "keyword-rule-rents",
    ruleTrace: [],
    ruleSourceTrace: [],
    sourceRow: SAMPLE_MANUAL_TABLE_ROWS[1],
    status: "mapped",
  },
  {
    ...SAMPLE_MANUAL_TABLE_ROWS[2],
    categoryId: "bank_fees",
    categoryLabel: "Bank Fees",
    confidence: 0.8,
    matchedKeyword: "bank charges",
    matchedRuleId: "keyword-rule-general-expenses",
    rowSourceTrace: [],
    ruleId: "keyword-rule-general-expenses",
    ruleTrace: [],
    ruleSourceTrace: [],
    sourceRow: SAMPLE_MANUAL_TABLE_ROWS[2],
    status: "mapped",
  },
  {
    ...SAMPLE_MANUAL_TABLE_ROWS[3],
    categoryId: "professional_fees",
    categoryLabel: "Professional Fees",
    confidence: 0.8,
    matchedKeyword: "professional fees",
    matchedRuleId: "keyword-rule-accounting-expenses",
    rowSourceTrace: [],
    ruleId: "keyword-rule-accounting-expenses",
    ruleTrace: [],
    ruleSourceTrace: [],
    sourceRow: SAMPLE_MANUAL_TABLE_ROWS[3],
    status: "mapped",
  },
  {
    ...SAMPLE_MANUAL_TABLE_ROWS[4],
    categoryId: "other_income",
    categoryLabel: "Other Income",
    confidence: 0.7,
    matchedKeyword: "other revenue",
    matchedRuleId: "keyword-rule-other-fapi-income",
    rowSourceTrace: [],
    ruleId: "keyword-rule-other-fapi-income",
    ruleTrace: [],
    ruleSourceTrace: [],
    sourceRow: SAMPLE_MANUAL_TABLE_ROWS[4],
    status: "mapped",
  },
];
