import type { CalculationRule } from "./schema";

export const SAMPLE_CALCULATION_RULES: CalculationRule[] = [
  {
    calculationId: "A",
    description: "A = max(income_bucket - expense_bucket, 0)",
    label: "A",
    operands: ["income_bucket", "expense_bucket"],
    operation: "max_subtract_zero",
    resultKey: "A",
  },
  {
    calculationId: "A1",
    description: "A1 = debtForgiveness * 2",
    label: "A1",
    operands: ["debtForgiveness", 2],
    operation: "multiply",
    resultKey: "A1",
  },
  {
    calculationId: "A2",
    description: "A2 = priorYearG",
    label: "A2",
    operands: ["priorYearG"],
    operation: "pass_through",
    resultKey: "A2",
  },
  {
    calculationId: "B",
    description: "B = capGains * inclusionRate",
    label: "B",
    operands: ["capGains", "inclusionRate"],
    operation: "multiply",
    resultKey: "B",
  },
  {
    calculationId: "C",
    description: "C = cfaIncome",
    label: "C",
    operands: ["cfaIncome"],
    operation: "pass_through",
    resultKey: "C",
  },
  {
    calculationId: "D",
    description: "D = businessLosses",
    label: "D",
    operands: ["businessLosses"],
    operation: "pass_through",
    resultKey: "D",
  },
  {
    calculationId: "E",
    description: "E = faclCarryforward",
    label: "E",
    operands: ["faclCarryforward"],
    operation: "pass_through",
    resultKey: "E",
  },
  {
    calculationId: "F",
    description: "F = prescribedAmount",
    label: "F",
    operands: ["prescribedAmount"],
    operation: "pass_through",
    resultKey: "F",
  },
  {
    calculationId: "F1",
    description: "F1 = prescribedAmountF1",
    label: "F1",
    operands: ["prescribedAmountF1"],
    operation: "pass_through",
    resultKey: "F1",
  },
  {
    calculationId: "G",
    description: "G = dividendDeductions",
    label: "G",
    operands: ["dividendDeductions"],
    operation: "pass_through",
    resultKey: "G",
  },
  {
    calculationId: "H",
    description: "H = partnershipDividends",
    label: "H",
    operands: ["partnershipDividends"],
    operation: "pass_through",
    resultKey: "H",
  },
  {
    calculationId: "GROSS",
    description: "Gross = A + A1 + A2 + B + C",
    label: "Gross",
    operands: ["A", "A1", "A2", "B", "C"],
    operation: "add",
    resultKey: "GROSS",
  },
  {
    calculationId: "DEDUCTIONS",
    description: "Deductions = D + E + F + F1 + G + H",
    label: "Deductions",
    operands: ["D", "E", "F", "F1", "G", "H"],
    operation: "add",
    resultKey: "DEDUCTIONS",
  },
  {
    calculationId: "FAPI_BRUT",
    description: "FAPI Brut = max(GROSS - DEDUCTIONS, 0)",
    label: "FAPI Brut",
    operands: ["GROSS", "DEDUCTIONS"],
    operation: "max_subtract_zero",
    resultKey: "FAPI_BRUT",
  },
  {
    calculationId: "FAT_DEDUCTION",
    description: "FAT Deduction = min(max(FAT_PAID, 0) * RTF, FAPI_BRUT)",
    label: "FAT Deduction",
    operands: ["FAT_PAID", "RTF", "FAPI_BRUT"],
    operation: "min_multiply_cap",
    resultKey: "FAT_DEDUCTION",
  },
  {
    calculationId: "NET_FAPI",
    description: "Net FAPI = max(FAPI_BRUT - FAT_DEDUCTION, 0)",
    label: "Net FAPI",
    operands: ["FAPI_BRUT", "FAT_DEDUCTION"],
    operation: "max_subtract_zero",
    resultKey: "NET_FAPI",
  },
  {
    calculationId: "NET_FAPI_CAD",
    description: "Net FAPI CAD = NET_FAPI * FX_RATE",
    label: "Net FAPI CAD",
    operands: ["NET_FAPI", "FX_RATE"],
    operation: "multiply",
    resultKey: "NET_FAPI_CAD",
  },
];
