// Generated by scripts/generate-workflow-schemas.mjs. Do not edit manually.

import { z } from 'zod';

import { migrateWorkflowRelationship } from './migrations';

// Storage serializes Date values as ISO strings; restore valid dates on read.

const storedDate = z.union([z.date(), z.string().datetime({ offset: true }).transform(value => new Date(value))]);

export const WorkflowLibrarySchema: z.ZodType<import("./library-types").WorkflowLibrary, z.ZodTypeDef, unknown> = z.lazy(() => z.record(PersonalWorkflowSchema));

export const PersonalWorkflowSchema: z.ZodType<import("./library-types").PersonalWorkflow, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "id": z.string(),
  "templateId": z.string(),
  "draft": LocalWorkflowSnapshotSchema,
  "versions": z.array(z.object({
  "number": z.number().finite(),
  "savedAt": z.string(),
  "definition": LocalWorkflowSnapshotSchema,
}).passthrough()),
  "sessions": z.array(WorkflowSessionSchema).optional(),
  "runs": z.array(z.object({
  "version": z.number().finite(),
  "at": z.string(),
  "result": LocalToolRunnerResultSchema,
  "requestId": z.string().optional(),
  "initiatedBy": z.object({
  "actorId": z.string(),
  "workspaceId": z.string(),
  "surface": z.union([z.literal("builder"), z.literal("run"), z.literal("chat")]),
}).passthrough().optional(),
}).passthrough()),
}).passthrough());

export const LocalWorkflowSnapshotSchema: z.ZodType<import("./domain/workflow-types").LocalWorkflowSnapshot, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "schemaVersion": z.literal("workflow-studio.local.v1"),
  "id": z.string(),
  "name": z.string(),
  "description": z.string(),
  "status": WorkflowDefinitionStatusSchema,
  "metadata": z.object({
  "kind": z.literal("generic-fiscal-workflow"),
  "sampleWorkflow": z.object({
  "id": z.string(),
  "label": z.string(),
  "description": z.string(),
}).passthrough().optional(),
  "tags": z.array(z.string()),
  "createdBy": z.string(),
  "createdAt": z.string(),
  "updatedBy": z.string(),
  "updatedAt": z.string(),
  "notes": z.string().optional(),
}).passthrough(),
  "blocks": z.array(WorkflowBlockSchema),
  "edges": z.array(WorkflowEdgeSchema),
  "structure": WorkflowStructureSchema,
  "runtimeUiConfig": RuntimeUiConfigSchema,
  "outputMappingPreview": OutputMappingPreviewSchema,
  "mockRuns": z.array(BlockRunSchema),
  "versionSnapshots": z.array(WorkflowVersionSnapshotSchema),
  "latestPublishedVersionId": z.string().optional(),
  "publishedVersion": z.object({
  "id": z.string(),
  "versionNumber": z.number().finite(),
  "createdAt": z.string(),
}).passthrough().optional(),
  "aiProposals": z.array(AiProposalSchema),
  "events": z.array(WorkflowEventSchema),
}).passthrough());

export const WorkflowSessionSchema: z.ZodType<import("./library-types").WorkflowSession, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "id": z.string(),
  "version": z.number().finite(),
  "revision": z.number().finite(),
  "createdAt": z.string(),
  "paused": z.boolean(),
  "approvedAt": z.string().optional(),
  "results": z.record(ToolRunResultSchema),
  "stale": z.array(z.string()),
  "reviewed": z.array(z.string()),
  "sources": z.array(z.object({
  "id": z.string(),
  "blockId": z.string(),
  "name": z.string(),
  "at": z.string(),
  "mode": z.union([z.literal("replace"), z.literal("add")]),
  "rows": z.array(z.record(z.unknown())),
}).passthrough()),
  "attempts": z.array(z.object({
  "at": z.string(),
  "revision": z.number().finite(),
  "blockId": z.string(),
  "result": LocalToolRunnerResultSchema,
}).passthrough()),
}).passthrough());

export const LocalToolRunnerResultSchema: z.ZodType<import("./execution-result").LocalToolRunnerResult, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "blockStatuses": z.record(z.union([z.literal("error"), z.literal("success")])),
  "edgeStatuses": z.record(LocalEdgeRunStatusSchema),
  "record": LocalRunRecordSchema,
  "result": WorkflowRunResultSchema,
}).passthrough());

export const WorkflowDefinitionStatusSchema: z.ZodType<import("./domain/block-types").WorkflowDefinitionStatus, z.ZodTypeDef, unknown> = z.lazy(() => z.union([z.literal("draft"), z.literal("published")]));

export const WorkflowBlockSchema: z.ZodType<import("./domain/workflow-types").WorkflowBlock, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "id": z.string(),
  "family": BlockFamilySchema,
  "subtype": BlockSubtypeSchema,
  "label": z.string(),
  "description": z.string(),
  "status": BlockStatusSchema,
  "position": WorkflowPositionSchema,
  "config": z.record(z.unknown()),
  "code": WorkflowCodeFieldSchema.optional(),
  "formula": WorkflowFormulaFieldSchema.optional(),
  "source": SourceMetadataSchema.optional(),
  "governance": GovernanceMetadataSchema.optional(),
  "runtime": RuntimeVisibilitySchema,
  "catalogId": z.string().optional(),
  "sample": z.union([z.literal(false), z.literal(true)]).optional(),
  "createdBy": z.string(),
  "createdAt": z.string(),
  "updatedBy": z.string(),
  "updatedAt": z.string(),
}).passthrough());

export const WorkflowEdgeSchema: z.ZodType<import("./domain/workflow-types").WorkflowEdge, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "id": z.string(),
  "sourceBlockId": z.string(),
  "targetBlockId": z.string(),
  "relationshipType": WorkflowRelationshipTypeSchema,
  "reason": z.string(),
  "sourceOutputRole": z.string().optional(),
  "targetInputRole": z.string().optional(),
  "bindingLabel": z.string().optional(),
  "bindingStatus": EdgeBindingStatusSchema,
  "status": EdgeStatusSchema,
  "createdBy": z.string(),
  "createdAt": z.string(),
  "confidence": z.number().finite(),
  "notes": z.string(),
  "history": z.array(WorkflowEdgeHistoryEntrySchema),
}).passthrough());

export const WorkflowStructureSchema: z.ZodType<import("./domain/workflow-types").WorkflowStructure, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "layout": z.literal("canvas-columns"),
  "entryBlockId": z.string().optional(),
  "blockOrder": z.array(z.string()),
  "columns": z.array(z.object({
  "id": z.string(),
  "family": BlockFamilySchema,
  "label": z.string(),
  "blockIds": z.array(z.string()),
}).passthrough()),
}).passthrough());

export const RuntimeUiConfigSchema: z.ZodType<import("./domain/workflow-types").RuntimeUiConfig, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "runtimeConfigId": z.string(),
  "sourceWorkflowId": z.string(),
  "sourceSnapshotId": z.string().optional(),
  "generatedAt": z.string(),
  "sections": z.array(RuntimeUiSectionSchema),
  "visibleRows": z.array(z.string()),
  "hiddenRows": z.array(z.string()),
  "reviewerOnlyRows": z.array(z.string()),
  "advancedRows": z.array(z.string()),
  "allowedActions": z.array(z.string()),
}).passthrough());

export const OutputMappingPreviewSchema: z.ZodType<import("./domain/workflow-types").OutputMappingPreview, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "id": z.string(),
  "sourceWorkflowId": z.string(),
  "sourceSnapshotId": z.string().optional(),
  "generatedAt": z.string(),
  "outputs": z.array(OutputMappingPreviewItemSchema),
}).passthrough());

export const BlockRunSchema: z.ZodType<import("./domain/workflow-types").BlockRun, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "id": z.string(),
  "blockId": z.string(),
  "blockLabel": z.string(),
  "status": BlockRunStatusSchema,
  "startedAt": z.string(),
  "completedAt": z.union([z.null(), z.string()]),
  "durationMs": z.union([z.null(), z.number().finite()]),
  "input": z.unknown().optional(),
  "output": z.unknown().optional(),
  "error": z.object({
  "message": z.string(),
}).passthrough().optional(),
}).passthrough());

export const WorkflowVersionSnapshotSchema: z.ZodType<import("./domain/workflow-types").WorkflowVersionSnapshot, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "id": z.string(),
  "schemaVersion": z.literal("workflow-studio.local.v1"),
  "workflowId": z.string(),
  "workflowName": z.string(),
  "versionNumber": z.number().finite(),
  "label": z.string(),
  "status": WorkflowDefinitionStatusSchema,
  "createdBy": z.string(),
  "createdAt": z.string(),
  "changeSummary": z.string(),
  "blockCount": z.number().finite(),
  "edgeCount": z.number().finite(),
  "blockIds": z.array(z.string()),
  "edgeIds": z.array(z.string()),
  "blocks": z.array(WorkflowBlockSchema),
  "edges": z.array(WorkflowEdgeSchema),
  "structure": WorkflowStructureSchema,
  "runtimeUiConfig": RuntimeUiConfigSchema,
  "outputMappingPreview": OutputMappingPreviewSchema,
  "aiProposals": z.array(AiProposalSchema),
  "mockRuns": z.array(BlockRunSchema),
  "notes": z.string().optional(),
  "validationWarnings": z.array(z.string()),
}).passthrough());

export const AiProposalSchema: z.ZodType<import("./domain/workflow-types").AiProposal, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "id": z.string(),
  "title": z.string().optional(),
  "originalPrompt": z.string(),
  "interpretedPlan": z.string(),
  "selectedTools": z.array(z.string()),
  "generatedBlocks": z.array(WorkflowBlockSchema),
  "generatedEdges": z.array(WorkflowEdgeSchema),
  "generatedCodeOrFormulas": z.array(z.object({
  "blockId": z.string(),
  "kind": z.union([z.literal("code"), z.literal("formula")]),
  "value": z.string(),
}).passthrough()),
  "status": AiProposalStatusSchema,
  "approvalResult": z.object({
  "approvedBy": z.string(),
  "approvedAt": z.string(),
  "notes": z.string().optional(),
}).passthrough().optional(),
  "rejectionResult": z.object({
  "rejectedBy": z.string(),
  "rejectedAt": z.string(),
  "reason": z.string(),
}).passthrough().optional(),
  "createdAt": z.string(),
  "createdBy": z.string().optional(),
  "relatedSelectedBlockId": z.string().optional(),
  "relatedSelectedEdgeId": z.string().optional(),
  "confidence": z.number().finite().optional(),
  "notes": z.string().optional(),
  "history": z.array(AiProposalHistoryEntrySchema).optional(),
}).passthrough());

export const WorkflowEventSchema: z.ZodType<import("./domain/workflow-types").WorkflowEvent, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "id": z.string(),
  "type": WorkflowEventTypeSchema,
  "message": z.string(),
  "createdAt": z.string(),
  "createdBy": z.string(),
  "details": z.record(z.unknown()).optional(),
}).passthrough());

export const ToolRunResultSchema: z.ZodType<import("./tool-types").ToolRunResult, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "blockTest": z.object({
  "mode": z.literal("isolated"),
  "inputs": z.union([z.literal("none"), z.literal("examples"), z.literal("recorded")]),
}).passthrough().optional(),
  "configSignature": z.string().optional(),
  "input": z.record(z.unknown()).optional(),
  "inputTransfers": z.array(z.object({
  "edgeId": z.string(),
  "sourceBlockId": z.string(),
  "sourceLabel": z.string(),
  "sourceOutputRole": z.string().optional(),
  "targetInputRole": z.string().optional(),
  "delivered": z.boolean(),
  "output": z.record(z.unknown()),
}).passthrough()).optional(),
  "runId": z.string(),
  "blockId": z.string(),
  "toolId": z.string(),
  "status": ToolRunStatusSchema,
  "output": z.record(z.unknown()),
  "logs": z.array(ToolRunLogSchema),
  "warnings": z.array(z.string()),
  "errors": z.array(z.string()),
  "evidenceRefs": z.array(EvidenceRefSchema),
  "sourceTrace": z.array(SourceTraceRefSchema),
  "confidence": z.number().finite().optional(),
  "startedAt": z.string(),
  "completedAt": z.string(),
}).passthrough());

export const LocalEdgeRunStatusSchema: z.ZodType<import("./execution-result").LocalEdgeRunStatus, z.ZodTypeDef, unknown> = z.lazy(() => z.union([z.literal("error"), z.literal("success"), z.literal("warning")]));

export const LocalRunRecordSchema: z.ZodType<import("./domain/workflow-types").LocalRunRecord, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "execution": LocalWorkflowExecutionSchema,
  "logs": z.array(LocalExecutionLogSchema),
}).passthrough());

export const WorkflowRunResultSchema: z.ZodType<import("./tool-types").WorkflowRunResult, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "runId": z.string(),
  "workflowId": z.string(),
  "workflowName": z.string(),
  "status": ToolRunStatusSchema,
  "startedAt": z.string(),
  "completedAt": z.string(),
  "results": z.array(ToolRunResultSchema),
  "logs": z.array(ToolRunLogSchema),
  "warnings": z.array(z.string()),
  "errors": z.array(z.string()),
}).passthrough());

export const BlockFamilySchema: z.ZodType<import("./domain/block-types").BlockFamily, z.ZodTypeDef, unknown> = z.lazy(() => z.union([z.literal("Trigger"), z.literal("Source"), z.literal("Logic"), z.literal("Review / Validation"), z.literal("Field"), z.literal("Output"), z.literal("AI / Agent"), z.literal("Protected")]));

export const BlockSubtypeSchema: z.ZodType<import("./domain/block-types").BlockSubtype, z.ZodTypeDef, unknown> = z.lazy(() => z.union([z.literal("Manual / On Demand"), z.literal("Schedule / Cron"), z.literal("Webhook / API Event"), z.literal("Manual Entry"), z.literal("Excel / Workbook"), z.literal("PDF / Document"), z.literal("API / HTTP Request"), z.literal("Database Query"), z.literal("Web / URL"), z.literal("AI Search Result"), z.literal("Currency Rate"), z.literal("Keyword Rules"), z.literal("Aggregation Rules"), z.literal("Rollup Rules"), z.literal("Calculation Rules"), z.literal("Category Rollup Aggregator"), z.literal("Calculation Engine"), z.literal("Hierarchy Aggregator"), z.literal("Classification / Mapping"), z.literal("Field Block"), z.literal("CSV Export"), z.literal("Excel Export"), z.literal("PDF Report"), z.literal("Evidence Pack"), z.literal("Canonical JSON"), z.literal("Taxprep Handoff"), z.literal("ONESOURCE Handoff"), z.literal("AI Search"), z.literal("AI Mapping Suggestion"), z.literal("AI Formula Proposal"), z.literal("AI Workflow Proposal"), z.literal("Excel Table Reader"), z.literal("PDF Text Parser"), z.literal("PDF Table Parser"), z.literal("OCR Extractor"), z.literal("API Response Parser"), z.literal("Formula"), z.literal("Script"), z.literal("Condition"), z.literal("Aggregation"), z.literal("Transformation"), z.literal("Approval Gate"), z.literal("Required Input Check"), z.literal("Missing Source Check"), z.literal("Unmatched Rows Check"), z.literal("Low Confidence Warning"), z.literal("Formula Consistency Check"), z.literal("Manual Override Review"), z.literal("Output Readiness Check"), z.literal("Protected Input"), z.literal("Protected Result"), z.literal("Official Line"), z.literal("Locked Rate"), z.literal("Final Reviewed Amount")]));

export const BlockStatusSchema: z.ZodType<import("./domain/block-types").BlockStatus, z.ZodTypeDef, unknown> = z.lazy(() => z.union([z.literal("error"), z.literal("running"), z.literal("configured"), z.literal("success"), z.literal("draft"), z.literal("needs-review"), z.literal("approved"), z.literal("locked")]));

export const WorkflowPositionSchema: z.ZodType<import("./domain/workflow-types").WorkflowPosition, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "x": z.number().finite(),
  "y": z.number().finite(),
}).passthrough());

export const WorkflowCodeFieldSchema: z.ZodType<import("./domain/workflow-types").WorkflowCodeField, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "language": z.union([z.literal("text"), z.literal("json"), z.literal("typescript"), z.literal("javascript"), z.literal("sql")]),
  "body": z.string(),
  "entrypoint": z.string().optional(),
}).passthrough());

export const WorkflowFormulaFieldSchema: z.ZodType<import("./domain/workflow-types").WorkflowFormulaField, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "expression": z.string(),
  "outputKey": z.string(),
  "inputs": z.array(z.string()),
}).passthrough());

export const SourceMetadataSchema: z.ZodType<import("./domain/workflow-types").SourceMetadata, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "sourceType": z.union([z.literal("Manual Entry"), z.literal("Excel / Workbook"), z.literal("PDF / Document"), z.literal("API / HTTP Request"), z.literal("Database Query"), z.literal("Web / URL"), z.literal("AI Search Result"), z.literal("Currency Rate"), z.literal("Keyword Rules"), z.literal("Aggregation Rules"), z.literal("Rollup Rules"), z.literal("Calculation Rules")]),
  "locator": z.string(),
  "valuePreview": z.string().optional(),
  "immutable": z.literal(true),
  "treatedAsEvidence": z.boolean(),
  "labelLocked": z.boolean(),
  "locatorLocked": z.boolean(),
  "valuesLocked": z.boolean(),
}).passthrough());

export const GovernanceMetadataSchema: z.ZodType<import("./domain/workflow-types").GovernanceMetadata, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "protected": z.boolean(),
  "protectedKind": z.union([z.literal("input"), z.literal("result"), z.literal("official-line"), z.literal("locked-rate"), z.literal("final-reviewed-amount"), z.literal("summary-result")]).optional(),
  "steward": z.string(),
  "lockedInRuntime": z.boolean(),
  "requiresUnlockToEdit": z.boolean(),
  "editIntent": z.string().optional(),
  "approvalState": z.union([z.literal("draft"), z.literal("approved"), z.literal("review-required")]),
}).passthrough());

export const RuntimeVisibilitySchema: z.ZodType<import("./domain/workflow-types").RuntimeVisibility, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "visible": z.boolean(),
  "editableInRuntime": z.boolean(),
  "generatedUiLocked": z.boolean(),
  "masked": z.boolean(),
  "showInRuns": z.boolean(),
  "outputKey": z.string().optional(),
}).passthrough());

export const WorkflowRelationshipTypeSchema: z.ZodType<import("./domain/edge-types").WorkflowRelationshipType, z.ZodTypeDef, unknown> = z.lazy(() => z.preprocess(migrateWorkflowRelationship, z.union([z.literal("provides_data_to"), z.literal("extracted_into"), z.literal("referenced_by"), z.literal("transforms_into"), z.literal("aggregates_into"), z.literal("branches_to"), z.literal("depends_on"), z.literal("checked_by"), z.literal("requires_review_by"), z.literal("triggers_validation"), z.literal("approves_for"), z.literal("blocks_until_resolved"), z.literal("certifies"), z.literal("feeds_protected_input"), z.literal("feeds_protected_result"), z.literal("feeds_output_input"), z.literal("included_in_output_preview"), z.literal("maps_to_output_candidate"), z.literal("feeds_ai_context"), z.literal("provides_context_to_ai"), z.literal("requests_ai_review"), z.literal("supplies_candidate_data"), z.literal("maps_to_output"), z.literal("included_in_handoff"), z.literal("proposes"), z.literal("suggests_mapping"), z.literal("suggests_formula"), z.literal("suggests_workflow_change"), z.literal("initiates")])));

export const EdgeBindingStatusSchema: z.ZodType<import("./domain/edge-types").EdgeBindingStatus, z.ZodTypeDef, unknown> = z.lazy(() => z.union([z.literal("invalid"), z.literal("warning"), z.literal("missing"), z.literal("valid")]));

export const EdgeStatusSchema: z.ZodType<import("./domain/edge-types").EdgeStatus, z.ZodTypeDef, unknown> = z.lazy(() => z.union([z.literal("active"), z.literal("disabled"), z.literal("rejected"), z.literal("proposed")]));

export const WorkflowEdgeHistoryEntrySchema: z.ZodType<import("./domain/edge-types").WorkflowEdgeHistoryEntry, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "id": z.string(),
  "action": z.union([z.literal("split"), z.literal("disabled"), z.literal("rejected"), z.literal("approved"), z.literal("created"), z.literal("updated"), z.literal("migrated")]),
  "by": z.string(),
  "at": z.string(),
  "notes": z.string().optional(),
}).passthrough());

export const RuntimeUiSectionSchema: z.ZodType<import("./domain/workflow-types").RuntimeUiSection, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "id": z.string(),
  "label": z.string(),
  "family": BlockFamilySchema,
  "rows": z.array(RuntimeUiRowSchema),
}).passthrough());

export const OutputMappingPreviewItemSchema: z.ZodType<import("./domain/workflow-types").OutputMappingPreviewItem, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "outputBlockId": z.string(),
  "outputLabel": z.string(),
  "outputSubtype": BlockSubtypeSchema,
  "readinessStatus": z.union([z.literal("ready"), z.literal("warning"), z.literal("missing")]),
  "mappedProtectedValues": z.array(z.object({
  "edgeId": z.string(),
  "protectedBlockId": z.string(),
  "protectedLabel": z.string(),
  "relationshipType": z.union([z.literal("maps_to_output"), z.literal("included_in_handoff")]),
}).passthrough()),
  "candidateLogicMappings": z.array(z.object({
  "edgeId": z.string(),
  "logicBlockId": z.string(),
  "logicLabel": z.string(),
  "relationshipType": z.union([z.literal("feeds_output_input"), z.literal("included_in_output_preview"), z.literal("maps_to_output_candidate")]),
}).passthrough()),
  "governanceWarnings": z.array(z.string()),
  "ignoredRelationshipCount": z.number().finite(),
  "missingRequirements": z.array(z.string()),
  "includedSourceTraceSetting": z.string(),
  "mockPayloadPreview": z.record(z.unknown()),
}).passthrough());

export const BlockRunStatusSchema: z.ZodType<import("./domain/block-types").BlockRunStatus, z.ZodTypeDef, unknown> = z.lazy(() => z.union([z.literal("skipped"), z.literal("error"), z.literal("running"), z.literal("pending"), z.literal("success"), z.literal("warning")]));

export const AiProposalStatusSchema: z.ZodType<import("./domain/workflow-types").AiProposalStatus, z.ZodTypeDef, unknown> = z.lazy(() => z.union([z.literal("rejected"), z.literal("approved"), z.literal("proposed")]));

export const AiProposalHistoryEntrySchema: z.ZodType<import("./domain/workflow-types").AiProposalHistoryEntry, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "id": z.string(),
  "action": z.union([z.literal("rejected"), z.literal("approved"), z.literal("created"), z.literal("revised")]),
  "by": z.string(),
  "at": z.string(),
  "notes": z.string().optional(),
}).passthrough());

export const WorkflowEventTypeSchema: z.ZodType<import("./domain/workflow-types").WorkflowEventType, z.ZodTypeDef, unknown> = z.lazy(() => z.union([z.literal("ai_proposal_approved"), z.literal("ai_proposal_created"), z.literal("ai_proposal_rejected"), z.literal("export_workflow"), z.literal("import_workflow"), z.literal("migration"), z.literal("publish_snapshot"), z.literal("reset_sample"), z.literal("save_draft"), z.literal("validation_warning"), z.literal("workflow_command")]));

export const ToolRunStatusSchema: z.ZodType<import("./tool-types").ToolRunStatus, z.ZodTypeDef, unknown> = z.lazy(() => z.union([z.literal("skipped"), z.literal("error"), z.literal("success"), z.literal("warning"), z.literal("needs_review")]));

export const ToolRunLogSchema: z.ZodType<import("./tool-types").ToolRunLog, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "id": z.string(),
  "at": z.string(),
  "level": z.union([z.literal("error"), z.literal("warning"), z.literal("info")]),
  "message": z.string(),
  "details": z.record(z.unknown()).optional(),
}).passthrough());

export const EvidenceRefSchema: z.ZodType<import("./tool-types").EvidenceRef, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "evidenceId": z.string(),
  "sourceBlockId": z.string(),
  "sourceLabel": z.string(),
  "immutable": z.literal(true),
  "label": z.string().optional(),
  "locator": z.string().optional(),
  "rowId": z.string().optional(),
  "valuePreview": z.string().optional(),
}).passthrough());

export const SourceTraceRefSchema: z.ZodType<import("./tool-types").SourceTraceRef, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "sourceBlockId": z.string(),
  "sourceLabel": z.string(),
  "evidenceRefId": z.string().optional(),
  "relationshipPath": z.array(z.string()),
  "rowId": z.string().optional(),
  "valuePreview": z.string().optional(),
}).passthrough());

export const LocalWorkflowExecutionSchema: z.ZodType<import("./domain/workflow-types").LocalWorkflowExecution, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "id": z.string(),
  "workflowId": z.string(),
  "status": z.union([z.literal("error"), z.literal("running"), z.literal("pending"), z.literal("success"), z.literal("cancelled")]),
  "startedAt": storedDate,
  "completedAt": z.union([z.null(), storedDate]),
  "duration": z.union([z.null(), z.string()]),
  "error": z.union([z.null(), z.string()]),
}).passthrough());

export const LocalExecutionLogSchema: z.ZodType<import("./domain/workflow-types").LocalExecutionLog, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "id": z.string(),
  "executionId": z.string(),
  "nodeId": z.string(),
  "nodeName": z.string(),
  "nodeType": z.string(),
  "status": z.union([z.literal("error"), z.literal("running"), z.literal("pending"), z.literal("success")]),
  "startedAt": storedDate,
  "completedAt": z.union([z.null(), storedDate]),
  "duration": z.union([z.null(), z.string()]),
  "input": z.unknown().optional(),
  "output": z.unknown().optional(),
  "error": z.union([z.null(), z.string()]),
}).passthrough());

export const RuntimeUiRowSchema: z.ZodType<import("./domain/workflow-types").RuntimeUiRow, z.ZodTypeDef, unknown> = z.lazy(() => z.object({
  "id": z.string(),
  "blockId": z.string(),
  "label": z.string(),
  "family": BlockFamilySchema,
  "subtype": BlockSubtypeSchema,
  "visible": z.boolean(),
  "readOnly": z.boolean(),
  "locked": z.boolean(),
  "reviewerOnly": z.boolean(),
  "advancedOnly": z.boolean(),
  "sourceReadOnly": z.boolean(),
  "protectedLocked": z.boolean(),
  "outputKey": z.string().optional(),
  "allowedActions": z.array(z.string()),
}).passthrough());

