import type { ToolDefinition } from "../../../runtime/types";

export const keywordMapperDefinition: ToolDefinition = {
  defaultConfig: {
    conflictStrategy: "highest_confidence",
    lowConfidenceThreshold: 0.75,
    matchFields: ["account", "label", "description"],
    matchMode: "contains",
    unmatchedStrategy: "send_to_review",
  },
  description:
    "Classifies upstream rows into atomic categories using a connected Keyword Rulebook.",
  displayName: "Keyword Mapper",
  family: "Logic",
  inputRoles: [
    {
      acceptedFamilies: ["Source", "Logic"],
      acceptedOutputTypes: ["rows", "mapped_rows", "parsed_table"],
      acceptedSourceKinds: [
        "excel_template_mock",
        "manual_table",
        "parsed_table",
        "uploaded_rows_mock",
      ],
      allowMultiple: true,
      description: "Tabular fiscal rows from a Source or upstream Logic tool.",
      id: "data_rows",
      label: "Data rows",
      required: true,
    },
    {
      acceptedFamilies: ["Source"],
      acceptedSourceKinds: ["keyword_rules"],
      allowMultiple: true,
      description: "Keyword-to-category rules provided by a Keyword Rulebook.",
      id: "keyword_rules",
      label: "Keyword rules",
      required: true,
    },
  ],
  outputRoles: [
    {
      canRouteToFamilies: ["Logic", "Output", "Review / Validation"],
      description: "Rows mapped to atomic categories.",
      id: "mapped_rows",
      label: "Mapped rows",
      outputKey: "mappedRows",
      outputType: "mapped_rows",
      samplePreview: "5 mapped rows",
    },
    {
      canRouteToFamilies: ["Review / Validation"],
      description: "Rows that did not match any keyword rule.",
      id: "unmatched_rows",
      label: "Unmatched rows",
      outputKey: "unmatchedRows",
      outputType: "unmatched_rows",
      samplePreview: "0 unmatched rows",
    },
    {
      canRouteToFamilies: ["Review / Validation"],
      description: "Mapped rows below the configured confidence threshold.",
      id: "low_confidence_rows",
      label: "Low-confidence rows",
      outputKey: "lowConfidenceRows",
      outputType: "low_confidence_rows",
      samplePreview: "1 low-confidence row",
    },
    {
      canRouteToFamilies: ["Review / Validation"],
      description: "Rows that matched more than one keyword rule.",
      id: "conflicts",
      label: "Conflicts",
      outputKey: "conflicts",
      outputType: "conflicts",
      samplePreview: "0 conflicts",
    },
    {
      canRouteToFamilies: ["Output", "Review / Validation"],
      description: "Counts and totals for mapped categories.",
      id: "mapping_summary",
      label: "Mapping summary",
      outputKey: "mappingSummary",
      outputType: "mapping_summary",
      samplePreview: "category counts and totals",
    },
  ],
  runMode: "local_mock",
  subtype: "Classification / Mapping",
  toolGroup: "mapping",
  toolId: "logic.keyword_mapper",
};
